Repository kubeshop/botkube, pull requests merged in 2022-05, with the labels that each got.

#578 Support extra K8s resources creation during Helm chart installation
  helm/botkube/README.md
  helm/botkube/templates/extraobjects.yaml
  helm/botkube/values.yaml
Labels: ready-to-merge

#580 Make the release script cross-platform
  .gitignore
  hack/release.sh
Labels: enhancement, ready-to-merge

#581 Fix writing cache for kubectl exec commands
  deploy-all-in-one-tls.yaml
  deploy-all-in-one.yaml
  helm/botkube/templates/deployment.yaml
Labels: bug, ready-to-merge

#591 Set event TimeStamp if K8s event Series is not nil
  pkg/events/events.go
Labels: ready-to-merge

#583 Do not log full Slack event details in case of unmarshalling error
  pkg/bot/export_test.go
  pkg/bot/slack.go
  pkg/bot/slack_test.go
Labels: bug, ready-to-merge

#597 Add and describe opt to specify sensitive data via external secrets
  helm/botkube/templates/_helpers.tpl
  helm/botkube/templates/deployment.yaml
  helm/botkube/templates/sslcert.yaml
  helm/botkube/values.yaml
Labels: enhancement, documentation, ready-to-merge, helm-chart

#593 Use `golangci-lint` and resolve all found issues
  .github/workflows/artifacts.yml
  .github/workflows/ci.yml
  .golangci.yml
  CONTRIBUTING.md
  Makefile
  cmd/botkube/main.go
  go.mod
  go.sum
  hack/runtests.sh
  hack/update-gofmt.sh
  hack/verify-gofmt.sh
  hack/verify-golint.sh
  hack/verify-govet.sh
  pkg/bot/bot.go
  pkg/bot/discord.go
  pkg/bot/lark.go
  pkg/bot/mattermost.go
  pkg/bot/slack.go
  pkg/bot/slack_test.go
  pkg/bot/teams.go
  pkg/bot/teams_notif.go
  pkg/config/config.go
  pkg/controller/controller.go
  pkg/controller/upgrade.go
  pkg/events/events.go
  pkg/execute/default_executor.go
  pkg/execute/default_runner.go
  pkg/execute/executor.go
  pkg/filterengine/filterengine.go
  pkg/filterengine/filters/image_tag_checker.go
  pkg/filterengine/filters/ingress_validator.go
  pkg/filterengine/filters/namespace_checker.go
  pkg/filterengine/filters/node_event_checker.go
  pkg/filterengine/filters/object_annotation_checker.go
  pkg/filterengine/filters/pod_label_checker.go
  pkg/filterengine/filters/utils.go
  pkg/filterengine/global.go
  pkg/log/log.go
  pkg/metrics/metrics.go
  pkg/notify/discord.go
  pkg/notify/elasticsearch.go
  pkg/notify/mattermost.go
  pkg/notify/slack.go
  pkg/notify/webhook.go
  pkg/utils/diff.go
  pkg/utils/utils.go
  pkg/utils/utils_test.go
  test/e2e/comm_config.yaml
  test/e2e/command/botkube.go
  test/e2e/command/fake_executor.go
  test/e2e/command/kubectl.go
  test/e2e/e2e_test.go
  test/e2e/env/env.go
  test/e2e/filters/filters.go
  test/e2e/notifier/create/create.go
  test/e2e/notifier/delete/delete.go
  test/e2e/notifier/error/error.go
  test/e2e/resource_config.yaml
  test/e2e/welcome/welcome.go
  test/webhook/server.go
Labels: enhancement, ready-to-merge, ci
