Repository kubeshop/botkube, pull requests merged in 2022-10, with the labels that each got.

#780 Add Service to the default executor configuration, remove problematic emoji
  helm/botkube/README.md
  helm/botkube/values.yaml
  pkg/bot/teams.go
  pkg/controller/controller.go
  test/e2e/bots_test.go
Labels: bug

#782 Remove CHANGELOG.md
  .github/workflows/pr-build.yaml
  CHANGELOG.md
Labels: documentation

#781 Cherry-pick 0.14 RC1 bug fixes
  .github/workflows/pr-build.yaml
  CHANGELOG.md
  helm/botkube/README.md
  helm/botkube/values.yaml
  pkg/bot/teams.go
  pkg/controller/controller.go
  test/e2e/bots_test.go
Labels: bug

#778 Use color scheme in E2E tests
  test/e2e/bots_test.go
  test/e2e/bots_tester_test.go
  test/e2e/discord_driver_test.go
  test/e2e/slack_driver_test.go
Labels: enhancement

#787 Introduce interactive `kubectl` command selection
  go.mod
  go.sum
  pkg/bot/interactive/feedback.go
  pkg/bot/interactive/help.go
  pkg/bot/interactive/markdown.go
  pkg/bot/interactive/markdown_test.go
  pkg/bot/interactive/message.go
  pkg/bot/interactive/plaintext_test.go
  pkg/bot/interactive/testdata/TestInteractiveMessageToMarkdown/render_with_custom_headers_and_default_new_lines.golden.txt
  pkg/bot/interactive/testdata/TestInteractiveMessageToMarkdown/render_with_custom_new_lines_and_default_headers.golden.txt
  pkg/bot/interactive/testdata/TestInteractiveMessageToMarkdownMultiSelect.golden.txt
  pkg/bot/interactive/testdata/TestInteractiveMessageToPlaintext.golden.txt
  pkg/bot/slack_renderer.go
  pkg/bot/socketslack.go
  pkg/execute/errors.go
  pkg/execute/executor.go
  pkg/execute/factory.go
  pkg/execute/kubectl.go
  pkg/execute/kubectl_survey.go
  pkg/execute/kubectl_survey_msg.go
  pkg/execute/kubectl_survey_test.go
  pkg/execute/kubectl_test.go
Labels: enhancement, slack

#795 Add namespace dropdown, render other dropdowns dynamically based on context
  cmd/botkube/main.go
  go.mod
  go.sum
  helm/botkube/README.md
  helm/botkube/templates/clusterrole.yaml
  helm/botkube/templates/systemroles.yaml
  helm/botkube/values.yaml
  internal/storage/help.go
  pkg/bot/interactive/message.go
  pkg/bot/slack_renderer.go
  pkg/config/config.go
  pkg/execute/executor.go
  pkg/execute/factory.go
  pkg/execute/fake_kc_guard.go
  pkg/execute/kubectl.go
  pkg/execute/kubectl/merger.go
  pkg/execute/kubectl/merger_test.go
  pkg/execute/kubectl_survey.go
  pkg/execute/kubectl_survey_msg.go
  pkg/execute/kubectl_survey_test.go
  test/e2e/bots_test.go
Labels: enhancement, slack

#800 Support quotes for the `--cluster-name` flag
  pkg/bot/interactive/help.go
  pkg/bot/interactive/testdata/TestInteractiveMessageToMarkdown/render_with_custom_headers_and_default_new_lines.golden.txt
  pkg/bot/interactive/testdata/TestInteractiveMessageToMarkdown/render_with_custom_new_lines_and_default_headers.golden.txt
  pkg/bot/interactive/testdata/TestInteractiveMessageToPlaintext.golden.txt
  pkg/utils/utils.go
  pkg/utils/utils_test.go
Labels: bug

#803 Make event notifications actionable
  cmd/botkube/main.go
  helm/botkube/README.md
  helm/botkube/values.yaml
  pkg/bot/interactive/command.go
  pkg/bot/interactive/message.go
  pkg/bot/slack.go
  pkg/bot/slack_renderer.go
  pkg/bot/socketslack.go
  pkg/bot/teams.go
  pkg/execute/executor.go
  pkg/execute/factory.go
  pkg/execute/kubectl/commander.go
  pkg/execute/kubectl/commander_test.go
  pkg/execute/kubectl/guard.go
  pkg/execute/kubectl/guard_test.go
  pkg/format/msg.go
  pkg/format/short_msg.go
  test/e2e/bots_test.go
Labels: enhancement, slack

#801 Print kubectl command builder on `@Botkube k|kc|kubectl`, add tokens validation
  pkg/config/config_test.go
  pkg/config/testdata/TestLoadedConfigValidationErrors/all-token.yaml
  pkg/config/testdata/TestLoadedConfigValidationErrors/app-token-only.yaml
  pkg/config/testdata/TestLoadedConfigValidationErrors/app-token.yaml
  pkg/config/testdata/TestLoadedConfigValidationErrors/bot-token-only.yaml
  pkg/config/testdata/TestLoadedConfigValidationErrors/bot-token.yaml
  pkg/config/testdata/TestLoadedConfigValidationErrors/no-token.yaml
  pkg/config/validator.go
  pkg/execute/executor.go
  pkg/execute/factory.go
  pkg/execute/fake_kc_guard.go
  pkg/execute/kubectl_cmd_builder.go
  pkg/execute/kubectl_cmd_builder_msg.go
  pkg/execute/kubectl_cmd_builder_test.go
Labels: enhancement, slack

#810 Filter not supported verbs by interactive `kubectl`, improve telemetry for interactive Slack messages
  internal/analytics/noop_reporter.go
  internal/analytics/reporter.go
  internal/analytics/segment_reporter.go
  internal/analytics/segment_reporter_test.go
  internal/analytics/testdata/TestSegmentReporter_ReportCommand.json
  pkg/bot/discord.go
  pkg/bot/mattermost.go
  pkg/bot/slack.go
  pkg/bot/socketslack.go
  pkg/bot/teams.go
  pkg/execute/command/origin.go
  pkg/execute/edit.go
  pkg/execute/executor.go
  pkg/execute/factory.go
  pkg/execute/fake_kc_guard.go
  pkg/execute/helper_test.go
  pkg/execute/kubectl/guard.go
  pkg/execute/kubectl_cmd_builder.go
  pkg/execute/notifier.go
Labels: enhancement, slack

#812 Add opt to append filter when building the `kubectl` command
  pkg/bot/interactive/message.go
  pkg/bot/slack.go
  pkg/bot/slack_renderer.go
  pkg/bot/socketslack.go
  pkg/execute/executor.go
  pkg/execute/kubectl_cmd_builder.go
  pkg/execute/kubectl_cmd_builder_msg.go
  pkg/execute/kubectl_cmd_builder_test.go
Labels: enhancement, slack

#811 Print diff between expected and actual messages in e2e tests
  go.mod
  test/e2e/bots_test.go
  test/e2e/bots_tester_test.go
  test/e2e/diff_helpers_test.go
  test/e2e/discord_driver_test.go
  test/e2e/slack_driver_test.go
Labels: ci

#808 Output filtering
  internal/analytics/noop_reporter.go
  internal/analytics/reporter.go
  internal/analytics/segment_reporter.go
  internal/analytics/segment_reporter_test.go
  internal/analytics/testdata/TestSegmentReporter_ReportCommand.json
  pkg/bot/discord.go
  pkg/bot/mattermost.go
  pkg/bot/slack.go
  pkg/bot/socketslack.go
  pkg/bot/teams.go
  pkg/execute/edit.go
  pkg/execute/executor.go
  pkg/execute/executor_filter.go
  pkg/execute/executor_filter_test.go
  pkg/execute/factory.go
  pkg/execute/helper_test.go
  pkg/execute/kubectl_cmd_builder.go
  pkg/execute/kubectl_cmd_builder_test.go
  pkg/execute/notifier.go
  pkg/utils/utils.go
  pkg/utils/utils_test.go
  test/e2e/bots_test.go
Labels: enhancement

#818 Use real command guard and cached client, fix bug with orphan resource name
  cmd/botkube/main.go
  pkg/execute/factory.go
  pkg/execute/fake_kc_guard_test.go
  pkg/execute/kubectl/guard.go
  pkg/execute/kubectl/guard_test.go
  pkg/execute/kubectl_cmd_builder.go
  pkg/execute/kubectl_cmd_builder_msg.go
  pkg/execute/kubectl_cmd_builder_test.go
Labels: enhancement

#820 Response thread fix
  pkg/bot/slack.go
  pkg/bot/socketslack.go
Labels: bug

#809 The CONTRIBUTING.md file is outdated
  CONTRIBUTING.md
  test/README.md
Labels: documentation, community

#817 Add namespace label to default keyword, change filter placeholder
  pkg/execute/kubectl_cmd_builder.go
  pkg/execute/kubectl_cmd_builder_msg.go
  pkg/execute/kubectl_cmd_builder_test.go
Labels: enhancement

#822 Prevent resource deletion from the actionable notifications
  CONTRIBUTING.md
  comm_config.yaml.tpl
  global_config.yaml.tpl
  helm/botkube/Chart.yaml
  helm/botkube/README.md
  helm/botkube/README.tpl.md
  helm/botkube/values.yaml
  pkg/execute/kubectl/commander.go
  pkg/execute/kubectl/commander_test.go
Labels: enhancement, wip

#826 v0.15.0 Fixes / Enhancements
  pkg/bot/socketslack.go
  pkg/execute/executor_filter.go
Labels: bug

#827 Cherry-picked v0.15.0 Fixes / Enhancements (#826)
  pkg/bot/socketslack.go
  pkg/execute/executor_filter.go
Labels: bug
