Repository kubeshop/botkube, pull requests merged in 2022-06, with the labels that each got.

#603 Remove global variables, pass context across all components and improve error handling
  CONTRIBUTING.md
  cmd/botkube/main.go
  go.mod
  go.sum
  helm/botkube/templates/serviceaccount.yaml
  helm/botkube/values.yaml
  pkg/bot/bot.go
  pkg/bot/discord.go
  pkg/bot/lark.go
  pkg/bot/mattermost.go
  pkg/bot/slack.go
  pkg/bot/teams.go
  pkg/config/config.go
  pkg/controller/config_watcher.go
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  pkg/controller/message.go
  pkg/controller/upgrade.go
  pkg/events/events.go
  pkg/execute/executor.go
  pkg/execute/factory.go
  pkg/execute/resource.go
  pkg/filterengine/filterengine.go
  pkg/filterengine/filters/image_tag_checker.go
  pkg/filterengine/filters/ingress_validator.go
  pkg/filterengine/filters/namespace_checker.go
  pkg/filterengine/filters/node_event_checker.go
  pkg/filterengine/filters/object_annotation_checker.go
  pkg/filterengine/filters/object_annotation_checker_test.go
  pkg/filterengine/filters/pod_label_checker.go
  pkg/filterengine/filters/utils.go
  pkg/filterengine/global.go
  pkg/filterengine/with_all_filters.go
  pkg/httpsrv/server.go
  pkg/kube/client.go
  pkg/log/log.go
  pkg/metrics/metrics.go
  pkg/notify/discord.go
  pkg/notify/elasticsearch.go
  pkg/notify/lark.go
  pkg/notify/mattermost.go
  pkg/notify/notify.go
  pkg/notify/slack.go
  pkg/notify/webhook.go
  pkg/notify/webhook_test.go
  pkg/utils/diff.go
  pkg/utils/diff_test.go
  pkg/utils/jsonpath.go
  pkg/utils/lark.go
  pkg/utils/utils.go
  test/e2e/command/botkube.go
  test/e2e/e2e_test.go
  test/e2e/env/env.go
  test/e2e/filters/filters.go
  test/e2e/notifier/create/create.go
  test/e2e/notifier/delete/delete.go
  test/e2e/notifier/error/error.go
  test/e2e/notifier/update/update.go
  test/e2e/utils/utils.go
  test/webhook/server.go
Labels: enhancement, refactor, ready-to-merge

#601 Add support for cfg via env vars and define external volumes
  go.mod
  go.sum
  helm/botkube/README.md
  helm/botkube/templates/deployment.yaml
  helm/botkube/values.yaml
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/testdata/comm_config.yaml
Labels: enhancement, ready-to-merge, helm-chart, breaking

#616 Fix ServiceMonitor selector
  helm/botkube/templates/servicemonitor.yaml
Labels: bug, ready-to-merge

#611 Add option to build&push image on PR automatically
  .github/workflows/pr-image.yaml
  Makefile
  hack/goreleaser.sh
Labels: enhancement, ready-to-merge, ci

#622 Implement E2E tests against BotKube deployed on K8s and real Slack API
  .golangci.yml
  Makefile
  go.mod
  helm/botkube/values.yaml
  pkg/execute/executor.go
  pkg/execute/executor_test.go
  pkg/filterengine/filterengine.go
  pkg/filterengine/filters/ingress_validator.go
  pkg/filterengine/filters/ingress_validator_test.go
  pkg/utils/utils.go
  pkg/utils/utils_test.go
  test.Dockerfile
  test/doc.go
  tests/README.md
  tests/e2e/k8s_helpers_test.go
  tests/e2e/slack_test.go
  tests/e2e/slack_tester_test.go
Labels: enhancement, ready-to-merge
