Repository kubeshop/botkube, pull requests merged in 2022-11, with the labels that each got.

#783 Botkube extensibility design for sources and executors
  docs/proposal/2022-09-28-botkube-plugin-system.md
  docs/proposal/assets/dependency-injection.png
  docs/proposal/assets/hashicorp-go-plugin-architecture.png
  docs/proposal/assets/kubectl-executor-plugin.png
  docs/proposal/assets/kubernetes-source-plugin.png
  docs/proposal/assets/plugin-system.png
Labels: enhancement, documentation

#834 Work around empty K8s resources list which causes Botkube crash
  pkg/execute/kubectl/guard.go
  pkg/execute/kubectl/guard_test.go
  pkg/execute/kubectl/resource-normalizer.go
Labels: bug

#837 Wire execution of automated actions
  cmd/botkube/main.go
  helm/botkube/README.md
  helm/botkube/values.yaml
  pkg/action/provider.go
  pkg/bot/discord.go
  pkg/bot/interactive/message.go
  pkg/bot/interactive/message_test.go
  pkg/bot/mattermost.go
  pkg/bot/slack.go
  pkg/bot/slack_renderer.go
  pkg/bot/socketslack.go
  pkg/bot/teams.go
  pkg/config/config.go
  pkg/config/testdata/TestLoadConfigSuccess/actions.yaml
  pkg/config/testdata/TestLoadConfigSuccess/config.golden.yaml
  pkg/controller/controller.go
  pkg/events/events.go
  pkg/execute/command/origin.go
  pkg/execute/executor.go
  pkg/execute/kubectl_cmd_builder_msg.go
  pkg/execute/kubectl_cmd_builder_test.go
  pkg/notifier/notifier.go
  pkg/sink/elasticsearch.go
  pkg/sink/webhook.go
Labels: enhancement

#850 Prepare sources config for additional constraints
  global_config.yaml.tpl
  helm/botkube/README.md
  helm/botkube/e2e-test-values.yaml
  helm/botkube/values.yaml
  pkg/config/config.go
  pkg/config/testdata/TestLoadConfigSuccess/config-all.yaml
  pkg/config/testdata/TestLoadConfigSuccess/config.golden.yaml
  pkg/recommendation/export_test.go
  pkg/recommendation/resource_events.go
  pkg/recommendation/resource_events_test.go
  pkg/sources/sources.go
  pkg/sources/sources_test.go
Labels: enhancement, breaking

#853 Include node count in anonymous analytics
  go.mod
  go.sum
  helm/botkube/templates/systemroles.yaml
  internal/analytics/identity.go
  internal/analytics/segment_reporter.go
  internal/analytics/segment_reporter_test.go
  internal/analytics/testdata/TestSegmentReporter_RegisterCurrentIdentity.json
Labels: enhancement

#854 Support source constraints for event details and resource labels, annotations, name
  helm/botkube/README.md
  helm/botkube/e2e-test-values.yaml
  helm/botkube/values.yaml
  pkg/config/config.go
  pkg/config/testdata/TestLoadConfigSuccess/config-all.yaml
  pkg/config/testdata/TestLoadConfigSuccess/config.golden.yaml
  pkg/controller/controller.go
  pkg/events/events.go
  pkg/recommendation/ingress_backend_service_valid_test.go
  pkg/recommendation/ingress_tls_secret_valid_test.go
  pkg/recommendation/pod_labels_set_test.go
  pkg/recommendation/pod_no_latest_image_tag_test.go
  pkg/sources/registration.go
  pkg/sources/registration_test.go
  pkg/sources/sources.go
  test/e2e/bots_test.go
Labels: enhancement

#856 Improve Helm chart documentation for Actions and sources
  helm/botkube/README.md
  helm/botkube/values.yaml
Labels: bug

#852 Add support for list/enable/disable actions
  go.mod
  go.sum
  helm/botkube/templates/persistent-config.yaml
  pkg/bot/interactive/help.go
  pkg/bot/interactive/testdata/TestInteractiveMessageToMarkdown/render_with_custom_headers_and_default_new_lines.golden.txt
  pkg/bot/interactive/testdata/TestInteractiveMessageToMarkdown/render_with_custom_new_lines_and_default_headers.golden.txt
  pkg/bot/interactive/testdata/TestInteractiveMessageToPlaintext.golden.txt
  pkg/config/manager.go
  pkg/config/manager_test.go
  pkg/config/state.go
  pkg/config/state_test.go
  pkg/execute/action.go
  pkg/execute/executor.go
  pkg/execute/factory.go
  pkg/execute/helper_test.go
  test/e2e/bots_test.go
Labels: enhancement

#863 Fixup `kubectl` help wording
  pkg/bot/interactive/help.go
  pkg/bot/interactive/testdata/TestInteractiveMessageToMarkdown/render_with_custom_headers_and_default_new_lines.golden.txt
  pkg/bot/interactive/testdata/TestInteractiveMessageToMarkdown/render_with_custom_new_lines_and_default_headers.golden.txt
  pkg/bot/interactive/testdata/TestInteractiveMessageToPlaintext.golden.txt
Labels: bug

#864 Move actions list E2E test after initial help message
  test/e2e/bots_test.go
Labels: bug, ci

#866 Change links to the documentation
  CONTRIBUTING.md
  README.md
  build/Dockerfile
  docs/investigation/configuration/2022-06-14-policies.md
  docs/investigation/configuration/2022-06-15-cfg-syntax-issues.md
  examples/service-debugging/README.md
  helm/botkube/README.md
  helm/botkube/values.yaml
  pkg/bot/interactive/help.go
  pkg/bot/interactive/testdata/TestInteractiveMessageToMarkdown/render_with_custom_headers_and_default_new_lines.golden.txt
  pkg/bot/interactive/testdata/TestInteractiveMessageToMarkdown/render_with_custom_new_lines_and_default_headers.golden.txt
  pkg/bot/interactive/testdata/TestInteractiveMessageToPlaintext.golden.txt
  pkg/config/config_test.go
  pkg/config/validator.go
  pkg/execute/edit.go
  pkg/execute/edit_test.go
  pkg/execute/kubectl_cmd_builder.go
  test/README.md
  test/e2e/slack_helpers_test.go
Labels: documentation

#859 Describe how plugins can be consumed within Botkube core
  docs/proposal/2022-09-28-botkube-plugin-system.md
  docs/proposal/2022-11-22-botkube-plugins-integration.md
Labels: enhancement, documentation
