Repository kubeshop/botkube, pull requests merged in 2022-08, with the labels that each got.

#672 Add logic to handle communicator bindings in kubectl
  cmd/botkube/main.go
  helm/botkube/e2e-test-values.yaml
  pkg/bot/discord.go
  pkg/bot/mattermost.go
  pkg/bot/slack.go
  pkg/bot/teams.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/execute/executor.go
  pkg/execute/executor_test.go
  pkg/execute/factory.go
  pkg/execute/kubectl.go
  pkg/execute/kubectl/checker.go
  pkg/execute/kubectl/checker_test.go
  pkg/execute/kubectl/helpers_test.go
  pkg/execute/kubectl/merger.go
  pkg/execute/kubectl/merger_test.go
  pkg/execute/kubectl/resource-normalizer.go
  pkg/execute/kubectl_test.go
  pkg/execute/resource.go
  pkg/ptr/ptr.go
  test/e2e/slack_test.go
Labels: enhancement

#670 Handle multiple configurations for multiple bots and sinks
  cmd/botkube/main.go
  go.mod
  go.sum
  helm/botkube/e2e-test-values.yaml
  helm/botkube/templates/tests/e2e-test.yaml
  pkg/bot/bot.go
  pkg/bot/discord.go
  pkg/bot/discord_fmt.go
  pkg/bot/discord_test.go
  pkg/bot/mattermost.go
  pkg/bot/mattermost_fmt.go
  pkg/bot/mattermost_test.go
  pkg/bot/slack.go
  pkg/bot/slack_fmt.go
  pkg/bot/slack_test.go
  pkg/bot/teams.go
  pkg/bot/teams_test.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/testdata/TestLoadConfigSuccess/config-all.yaml
  pkg/config/testdata/TestLoadConfigSuccess/config.golden.yaml
  pkg/controller/notifier.go
  pkg/execute/executor.go
  pkg/execute/factory.go
  pkg/execute/notifier.go
  pkg/execute/notifier_test.go
  pkg/sink/elasticsearch.go
  test/README.md
  test/e2e/k8s_helpers_test.go
  test/e2e/slack_test.go
  test/e2e/slack_tester_test.go
Labels: enhancement, refactor

#677 Return executors enabled only in a given channel
  helm/botkube/e2e-test-values.yaml
  pkg/execute/executor.go
  pkg/execute/executor_test.go
  pkg/execute/factory.go
  pkg/execute/kubectl/merger.go
Labels: bug

#680 Fix merging order for executor bindings
  pkg/execute/kubectl/merger.go
  pkg/execute/kubectl/merger_test.go
Labels: bug

#678 Update Helm chart values description
  helm/botkube/README.md
  helm/botkube/values.yaml
Labels: enhancement, documentation

#687 Add ability to configure specific recommendations during BotKube installation/upgrade
  cmd/botkube/main.go
  docs/proposal/2022-06-14-configuration-bindings.md
  global_config.yaml.tpl
  helm/botkube/README.md
  helm/botkube/values.yaml
  pkg/config/config.go
  pkg/config/testdata/TestLoadConfigSuccess/config-all.yaml
  pkg/config/testdata/TestLoadConfigSuccess/config.golden.yaml
  pkg/controller/controller.go
  pkg/events/events.go
  pkg/filterengine/filterengine.go
  pkg/filterengine/filters/image_tag_checker.go
  pkg/filterengine/filters/ingress_validator.go
  pkg/filterengine/filters/ingress_validator_test.go
  pkg/filterengine/filters/namespace_checker.go
  pkg/filterengine/filters/node_event_checker.go
  pkg/filterengine/filters/object_annotation_checker.go
  pkg/filterengine/filters/pod_label_checker.go
  pkg/filterengine/filters/utils.go
  pkg/filterengine/with_all_filters.go
  pkg/recommendation/export_test.go
  pkg/recommendation/factory.go
  pkg/recommendation/factory_test.go
  pkg/recommendation/ingress_backend_service_valid.go
  pkg/recommendation/ingress_backend_service_valid_test.go
  pkg/recommendation/ingress_tls_secret_valid.go
  pkg/recommendation/ingress_tls_secret_valid_test.go
  pkg/recommendation/pod_labels_set.go
  pkg/recommendation/pod_labels_set_test.go
  pkg/recommendation/pod_no_latest_image_tag.go
  pkg/recommendation/pod_no_latest_image_tag_test.go
  pkg/recommendation/set.go
  test/e2e/slack_test.go
Labels: enhancement, refactor

#689 Merge recommendation configuration with override strategy
  pkg/config/config.go
  pkg/controller/controller.go
  pkg/recommendation/aggregated_runner.go
  pkg/recommendation/export_test.go
  pkg/recommendation/factory.go
  pkg/recommendation/factory_test.go
  pkg/recommendation/set.go
Labels: enhancement

#691 Support routing notifications to a given channel based on Kubernetes Sources
  cmd/botkube/main.go
  comm_config.yaml.tpl
  helm/botkube/README.md
  helm/botkube/e2e-test-values.yaml
  helm/botkube/values.yaml
  pkg/bot/discord.go
  pkg/bot/mattermost.go
  pkg/bot/slack.go
  pkg/bot/teams.go
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  pkg/controller/notifier.go
  pkg/filterengine/filterengine.go
  pkg/filterengine/with_all_filters.go
  pkg/sink/elasticsearch.go
  pkg/sink/webhook.go
  pkg/sliceutil/intersect.go
  pkg/sliceutil/intersect_test.go
  pkg/sources/registration.go
  pkg/sources/sources.go
  pkg/sources/sources_test.go
  test/e2e/slack_test.go
Labels: enhancement, refactor

#696 Handle recommendations even if no such resources are configured for notifications
  helm/botkube/e2e-test-values.yaml
  pkg/config/config.go
  pkg/controller/controller.go
  pkg/events/events.go
  pkg/ptr/ptr.go
  pkg/recommendation/export_test.go
  pkg/recommendation/factory.go
  pkg/recommendation/factory_test.go
  pkg/recommendation/resource_events.go
  pkg/recommendation/resource_events_test.go
  pkg/sources/sources.go
  pkg/sources/sources_test.go
Labels: enhancement

#699 Generate only draft release, and process chart during release
  .goreleaser.yml
  hack/release.sh
Labels: bug

#701 Ignore resource object when marshalling event to JSON
  pkg/events/events.go
Labels: bug

#702 Fix ingress manifest
  helm/botkube/templates/ingress.yaml
  pkg/config/config.go
  pkg/config/testdata/TestLoadConfigSuccess/config.golden.yaml
  pkg/execute/notifier.go
Labels: bug

#706 Make more robust getting the k8s version
  cmd/botkube/main.go
  pkg/execute/default_runner.go
  pkg/execute/executor.go
  pkg/execute/factory.go
  pkg/execute/kubectl.go
  pkg/execute/kubectl_test.go
Labels: enhancement

#700 Upgrade Go K8s dependencies to 1.25
  go.mod
  go.sum
Labels: bug

#695 Prepare Ingress recommendation example
  examples/README.md
  examples/ingress-recommendations/README.md
  examples/ingress-recommendations/botkube-values.yaml
  examples/ingress-recommendations/deploy-final/meme.yaml
  examples/ingress-recommendations/deploy-final/quote.yaml
  examples/ingress-recommendations/deploy/meme.yaml
  examples/ingress-recommendations/deploy/quote.yaml
  examples/ingress-recommendations/ingress-overrides.yaml
Labels: documentation

#692 Add example apps for use-case demos
  examples/src/.gitignore
  examples/src/README.md
  examples/src/assets/face-0.jpg
  examples/src/assets/face-1.jpg
  examples/src/assets/face-2.jpg
  examples/src/assets/face-3.jpg
  examples/src/assets/face-4.jpg
  examples/src/assets/face-5.jpg
  examples/src/assets/face-6.jpg
  examples/src/build/Dockerfile-meme
  examples/src/build/Dockerfile-quote
  examples/src/cmd/meme/main.go
  examples/src/cmd/quote/main.go
  examples/src/go.mod
  examples/src/go.sum
  examples/src/internal/meme/client.go
  examples/src/internal/meme/generator.go
  examples/src/internal/meme/handler.go
  examples/src/internal/quote/generator.go
  examples/src/internal/quote/handler.go
Labels: enhancement
