Repository kubeshop/botkube, pull requests merged in 2022-09, with the labels that each got.

#714 Add service debugging scenario
  examples/service-debugging/README.md
  examples/service-debugging/assets/create-events.png
  examples/service-debugging/assets/error-event.png
  examples/service-debugging/botkube-values.yaml
  examples/service-debugging/deploy-final/meme.yaml
  examples/service-debugging/deploy-final/quote.yaml
  examples/service-debugging/deploy/meme.yaml
  examples/service-debugging/deploy/quote.yaml
Labels: enhancement, documentation

#720 Use image registry when building single Docker image
  hack/goreleaser.sh
Labels: bug

#722 Disables analytics reporting when running e2e tests locally
  .github/workflows/branch-build.yml
  helm/botkube/e2e-test-values.yaml
Labels: enhancement

#724 Investigate persistent configuration for BotKube commands
  docs/investigation/configuration/2022-09-07-persistent-cfg-from-commands.md
  docs/investigation/configuration/assets/communicationsecret.yaml
Labels: enhancement, documentation

#693 Convert Slack Communication from RTM to WebSocket
  .github/workflows/branch-build.yml
  .gitignore
  .goreleaser.yml
  Makefile
  hack/goreleaser.sh
  pkg/bot/slack.go
  pkg/utils/struct_dumper.go
  pkg/utils/utils_test.go
  test/e2e/slack_tester_test.go
Labels: enhancement, slack

#725 Add interactive Help message for Slack platform
  .github/workflows/pr-build.yaml
  cmd/botkube/main.go
  pkg/bot/bot.go
  pkg/bot/discord.go
  pkg/bot/interactive/help.go
  pkg/bot/interactive/message.go
  pkg/bot/mattermost.go
  pkg/bot/slack.go
  pkg/bot/slack_fmt.go
  pkg/bot/slack_renderer.go
  pkg/bot/teams.go
  pkg/format/codeblock.go
  pkg/format/codeblock_test.go
  test/e2e/slack_helpers_test.go
  test/e2e/slack_test.go
  test/e2e/slack_tester_test.go
Labels: enhancement, slack

#732 Introduce Background Compatibility for Socket Mode
  comm_config.yaml.tpl
  helm/botkube/README.md
  helm/botkube/e2e-test-values.yaml
  helm/botkube/values.yaml
  pkg/bot/slack.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/testdata/TestLoadConfigSuccess/config.golden.yaml
  pkg/config/testdata/TestLoadedConfigValidationErrors/all-token.yaml
  pkg/config/testdata/TestLoadedConfigValidationErrors/app-token-only.yaml
  pkg/config/testdata/TestLoadedConfigValidationErrors/app-token.yaml
  pkg/config/testdata/TestLoadedConfigValidationErrors/bot-token-only.yaml
  pkg/config/testdata/TestLoadedConfigValidationErrors/bot-token.yaml
  pkg/config/testdata/TestLoadedConfigValidationErrors/no-token.yaml
  pkg/config/testdata/TestLoadedConfigValidationWarnings/executors-include-warning.yaml
  pkg/config/validator.go
  pkg/execute/notifier.go
Labels: enhancement

#740 Disable Discord E2E tests temporarily
  test/e2e/bots_test.go
Labels: bug, ci

#736 Support notifications and filters configuration via Helm
  cmd/botkube/main.go
  comm_config.yaml.tpl
  global_config.yaml.tpl
  helm/botkube/README.md
  helm/botkube/e2e-test-values.yaml
  helm/botkube/templates/global-config.yaml
  helm/botkube/values.yaml
  pkg/bot/bot.go
  pkg/bot/discord.go
  pkg/bot/mattermost.go
  pkg/bot/slack.go
  pkg/bot/teams.go
  pkg/config/config.go
  pkg/config/manager.go
  pkg/config/testdata/TestLoadConfigSuccess/config-all.yaml
  pkg/config/testdata/TestLoadConfigSuccess/config.golden.yaml
  pkg/execute/executor.go
  pkg/execute/factory.go
  pkg/execute/notifier.go
  pkg/execute/notifier_test.go
  pkg/filterengine/filterengine.go
  pkg/filterengine/filters/namespace_checker.go
  pkg/filterengine/filters/object_annotation_checker.go
  pkg/filterengine/with_all_filters.go
  pkg/sliceutil/intersect.go
  pkg/sources/sources.go
  pkg/sources/sources_test.go
  test/e2e/bots_test.go
Labels: enhancement

#727 Add command to get interactive help message
  cmd/botkube/main.go
  pkg/bot/discord.go
  pkg/bot/interactive/help.go
  pkg/bot/interactive/message.go
  pkg/bot/interactive/msg.go
  pkg/bot/interactive/msg_test.go
  pkg/bot/interactive/testdata/TestInteractiveMessageToMarkdown/render_with_MS_Teams_new_lines.golden.txt
  pkg/bot/interactive/testdata/TestInteractiveMessageToMarkdown/render_with_Markdown_new_lines.golden.txt
  pkg/bot/mattermost.go
  pkg/bot/slack.go
  pkg/bot/teams.go
  pkg/controller/notifier.go
  pkg/execute/executor.go
  pkg/execute/factory.go
  pkg/execute/kubectl.go
  pkg/execute/kubectl_test.go
  pkg/execute/notifier.go
  pkg/execute/notifier_test.go
  pkg/sink/elasticsearch.go
  pkg/sink/webhook.go
  test/README.md
  test/e2e/bots_test.go
  test/e2e/bots_tester_test.go
  test/e2e/discord_driver_test.go
  test/e2e/k8s_helpers_test.go
  test/e2e/slack_driver_test.go
Labels: enhancement, slack

#738 Persist sent help messages
  cmd/botkube/main.go
  helm/botkube/README.md
  helm/botkube/templates/botkube-cm.yaml
  helm/botkube/templates/deployment.yaml
  helm/botkube/templates/systemroles.yaml
  helm/botkube/values.yaml
  internal/storage/help.go
  pkg/config/config.go
  pkg/config/default.yaml
  pkg/config/testdata/TestLoadConfigSuccess/config.golden.yaml
  pkg/execute/notifier_test.go
  pkg/sources/sources.go
Labels: enhancement

#739 Define different k8s source presets, add option to set event list globally
  helm/botkube/README.md
  helm/botkube/e2e-test-values.yaml
  helm/botkube/values.yaml
  pkg/config/config.go
  pkg/config/testdata/TestLoadConfigSuccess/config-all.yaml
  pkg/config/testdata/TestLoadConfigSuccess/config.golden.yaml
  pkg/recommendation/resource_events.go
  pkg/sources/sources.go
  pkg/sources/sources_test.go
Labels: enhancement

#743 Add feedback cmd
  pkg/bot/bot.go
  pkg/bot/discord.go
  pkg/bot/interactive/feedback.go
  pkg/bot/interactive/help.go
  pkg/bot/interactive/message.go
  pkg/bot/interactive/testdata/TestInteractiveMessageToMarkdown/render_with_MS_Teams_new_lines.golden.txt
  pkg/bot/interactive/testdata/TestInteractiveMessageToMarkdown/render_with_Markdown_new_lines.golden.txt
  pkg/bot/mattermost.go
  pkg/bot/slack.go
  pkg/bot/slack_renderer.go
  pkg/bot/teams.go
  pkg/execute/executor.go
  pkg/execute/factory.go
Labels: enhancement

#747 Add option to edit source bindings
  go.mod
  helm/botkube/README.md
  helm/botkube/values.yaml
  pkg/bot/discord.go
  pkg/bot/interactive/help.go
  pkg/bot/interactive/markdown.go
  pkg/bot/interactive/markdown_test.go
  pkg/bot/interactive/message.go
  pkg/bot/interactive/testdata/TestInteractiveMessageToMarkdown/render_with_custom_headers_and_default_new_lines.golden.txt
  pkg/bot/interactive/testdata/TestInteractiveMessageToMarkdown/render_with_custom_new_lines_and_default_headers.golden.txt
  pkg/bot/interactive/testdata/TestInteractiveMessageToMarkdownMultiSelect.golden.txt
  pkg/bot/slack.go
  pkg/bot/slack_renderer.go
  pkg/bot/slack_utils.go
  pkg/bot/socketslack.go
  pkg/config/config.go
  pkg/config/manager.go
  pkg/config/testdata/TestLoadConfigSuccess/config.golden.yaml
  pkg/execute/default_runner.go
  pkg/execute/edit.go
  pkg/execute/edit_test.go
  pkg/execute/executor.go
  pkg/execute/factory.go
  pkg/execute/heleper_test.go
  pkg/execute/notifier.go
  pkg/execute/notifier_test.go
Labels: enhancement, slack

#746 Persist filters, notifications and source bindings state from commands
  cmd/botkube/main.go
  helm/botkube/README.md
  helm/botkube/e2e-test-values.yaml
  helm/botkube/templates/deployment.yaml
  helm/botkube/templates/persistent-config.yaml
  helm/botkube/values.yaml
  pkg/bot/bot.go
  pkg/bot/discord.go
  pkg/bot/mattermost.go
  pkg/bot/slack.go
  pkg/bot/slack_utils.go
  pkg/bot/socketslack.go
  pkg/bot/teams.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/export_test.go
  pkg/config/manager.go
  pkg/config/manager_test.go
  pkg/config/state.go
  pkg/config/testdata/TestLoadConfigSuccess/_aaa-special-file.yaml
  pkg/config/testdata/TestLoadConfigSuccess/config-global.yaml
  pkg/config/testdata/TestLoadConfigSuccess/config.golden.yaml
  pkg/controller/config_watcher.go
  pkg/controller/controller.go
  pkg/execute/edit.go
  pkg/execute/edit_test.go
  pkg/execute/executor.go
  pkg/execute/executor_test.go
  pkg/execute/factory.go
  pkg/execute/heleper_test.go
  pkg/execute/helper_test.go
  pkg/execute/notifier.go
  pkg/execute/notifier_test.go
  test/e2e/bots_test.go
Labels: enhancement

#759 Remove installation ID generation for anonymous analytics
  cmd/botkube/main.go
  helm/botkube/templates/analytics-config.yaml
  helm/botkube/templates/deployment.yaml
  helm/botkube/templates/global-config.yaml
  internal/analytics/identity.go
  internal/analytics/noop_reporter.go
  internal/analytics/reporter.go
  internal/analytics/segment_reporter.go
  internal/analytics/segment_reporter_test.go
  internal/analytics/testdata/TestSegmentReporter_RegisterCurrentIdentity.json
  internal/analytics/testdata/TestSegmentReporter_ReportBotEnabled.json
  internal/analytics/testdata/TestSegmentReporter_ReportCommand.json
  internal/analytics/testdata/TestSegmentReporter_ReportFatalError/Identity.json
  internal/analytics/testdata/TestSegmentReporter_ReportHandledEventError.json
  internal/analytics/testdata/TestSegmentReporter_ReportHandledEventSuccess.json
  internal/analytics/testdata/TestSegmentReporter_ReportSinkEnabled.json
  pkg/config/config.go
  pkg/config/testdata/TestLoadConfigSuccess/analytics.yaml
  pkg/config/testdata/TestLoadConfigSuccess/config.golden.yaml
  pkg/execute/notifier_test.go
Labels: bug

#762 Merge persistent config ConfigMaps between Helm upgrades
  helm/botkube/templates/persistent-config.yaml
Labels: enhancement

#761 Update message in help, and ignore modal activity
  pkg/bot/interactive/help.go
  pkg/bot/interactive/testdata/TestInteractiveMessageToMarkdown/render_with_custom_headers_and_default_new_lines.golden.txt
  pkg/bot/interactive/testdata/TestInteractiveMessageToMarkdown/render_with_custom_new_lines_and_default_headers.golden.txt
  pkg/bot/slack_renderer.go
  pkg/bot/socketslack.go
  pkg/execute/edit.go
  pkg/execute/edit_test.go
  pkg/execute/executor.go
  test/e2e/bots_test.go
Labels: bug

#771 Fix typo in feedback, remove redundant func args
  pkg/bot/interactive/feedback.go
  pkg/bot/socketslack.go
  pkg/execute/executor.go
Labels: enhancement

#751 Release Automation
  .github/release.yml
  .github/workflows/ci.yml
  .github/workflows/cut-new-release.yml
  .github/workflows/finalize-release.yml
  .github/workflows/next-rc.yml
  .github/workflows/process-chart.yml
  .github/workflows/release.yml
  .goreleaser.yml
  .release
  Makefile
  hack/goreleaser.sh
  hack/release.sh
Labels: enhancement, ci

#752 Support kubectl aliases
  pkg/execute/executor.go
  pkg/execute/kubectl.go
  pkg/execute/kubectl_test.go
  test/e2e/bots_test.go
Labels: enhancement

#770 Add analytics to slack interactive buttons
  internal/analytics/noop_reporter.go
  internal/analytics/reporter.go
  internal/analytics/segment_reporter.go
  internal/analytics/segment_reporter_test.go
  internal/analytics/testdata/TestSegmentReporter_ReportCommand.json
  pkg/bot/slack_renderer.go
  pkg/bot/socketslack.go
  pkg/execute/edit.go
  pkg/execute/executor.go
  pkg/execute/factory.go
  pkg/execute/helper_test.go
  pkg/execute/notifier.go
Labels: enhancement, slack

#776 Adjust formatting for help message and notification presets
  pkg/bot/interactive/help.go
  pkg/bot/interactive/testdata/TestInteractiveMessageToMarkdown/render_with_custom_headers_and_default_new_lines.golden.txt
  pkg/bot/interactive/testdata/TestInteractiveMessageToMarkdown/render_with_custom_new_lines_and_default_headers.golden.txt
  pkg/bot/slack_renderer.go
  pkg/execute/edit.go
  pkg/execute/edit_test.go
Labels: enhancement

#773 Render plain text for messages sent in attachments and remove the header
  helm/botkube/templates/service.yaml
  pkg/bot/discord.go
  pkg/bot/interactive/formatters.go
  pkg/bot/interactive/markdown.go
  pkg/bot/interactive/markdown_test.go
  pkg/bot/interactive/plaintext.go
  pkg/bot/interactive/plaintext_test.go
  pkg/bot/interactive/testdata/TestInteractiveMessageToPlaintext.golden.txt
  pkg/bot/interactive/testdata/TestInteractiveMessageToPlaintextMultiSelect.golden.txt
  pkg/bot/mattermost.go
  pkg/bot/slack.go
  pkg/bot/socketslack.go
  pkg/bot/teams.go
  test/e2e/bots_test.go
  test/e2e/bots_tester_test.go
  test/e2e/discord_driver_test.go
  test/e2e/slack_driver_test.go
Labels: bug

#779 Revert main branch
  .github/workflows/cut-new-release.yml
Labels: bug
