Repository kubeshop/botkube, pull requests merged in 2022-07, with the labels that each got.

#624 Run E2E integration tests on pull requests and branch build
  .github/workflows/artifacts.yml
  .github/workflows/branch-build.yml
  .github/workflows/pr-build.yaml
  .goreleaser.yml
  Makefile
  build/test.Dockerfile
  hack/goreleaser.sh
  hack/release.sh
  helm/botkube/e2e-test-values.yaml
  helm/botkube/templates/tests/e2e-test-rbac.yaml
  helm/botkube/templates/tests/e2e-test.yaml
  helm/botkube/values.yaml
  test.Dockerfile
  tests/README.md
Labels: enhancement, ready-to-merge

#625 Investigate analytics collection
  docs/investigation/analytics-collection.md
Labels: documentation, ready-to-merge

#633 Change go mod name
  .goreleaser.yml
  README.md
  cmd/botkube/main.go
  go.mod
  hack/goreleaser.sh
  pkg/bot/bot.go
  pkg/bot/discord.go
  pkg/bot/lark.go
  pkg/bot/mattermost.go
  pkg/bot/slack.go
  pkg/bot/teams.go
  pkg/bot/teams_notif.go
  pkg/controller/config_watcher.go
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  pkg/controller/message.go
  pkg/controller/upgrade.go
  pkg/events/events.go
  pkg/execute/executor.go
  pkg/execute/factory.go
  pkg/execute/resource.go
  pkg/filterengine/filterengine.go
  pkg/filterengine/filters/image_tag_checker.go
  pkg/filterengine/filters/ingress_validator.go
  pkg/filterengine/filters/ingress_validator_test.go
  pkg/filterengine/filters/namespace_checker.go
  pkg/filterengine/filters/namespace_checker_test.go
  pkg/filterengine/filters/node_event_checker.go
  pkg/filterengine/filters/object_annotation_checker.go
  pkg/filterengine/filters/pod_label_checker.go
  pkg/filterengine/filters/utils.go
  pkg/filterengine/with_all_filters.go
  pkg/notify/discord.go
  pkg/notify/elasticsearch.go
  pkg/notify/lark.go
  pkg/notify/mattermost.go
  pkg/notify/notify.go
  pkg/notify/slack.go
  pkg/notify/webhook.go
  pkg/utils/diff.go
  pkg/utils/diff_test.go
  test/e2e/slack_test.go
Labels: refactor

#635 Revert "Add lark notification and bot support"
  cmd/botkube/main.go
  go.mod
  go.sum
  helm/botkube/templates/ingress.yaml
  helm/botkube/templates/service.yaml
  helm/botkube/values.yaml
  pkg/bot/lark.go
  pkg/bot/utils.go
  pkg/config/config.go
  pkg/execute/executor.go
  pkg/notify/lark.go
  pkg/notify/notify.go
  pkg/utils/lark.go
Labels: refactor

#637 Remove last chart release, remove www from botkube's urls
  .github/workflows/branch-build.yml
  CONTRIBUTING.md
  README.md
  docs/investigation/configuration/2022-06-14-policies.md
  docs/investigation/configuration/2022-06-15-cfg-syntax-issues.md
  helm/botkube/Chart.yaml
  helm/botkube/README.md
  test/README.md
Labels: enhancement, ci

#639 Add Artifact Hub meta file
  README.md
  artifacthub-repo.yml
Labels: enhancement

#638 Add community files
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  README.md
  SECURITY.md
  docs/assets/botkube-title.jpg
  docs/assets/botkube_arch.jpg
  docs/assets/github-clone.png
  docs/assets/github-fork.png
  docs/assets/icons/bug-line.svg
  docs/assets/icons/cloud-line.svg
  docs/assets/icons/question-answer-line.svg
  docs/assets/icons/stack-line.svg
  docs/assets/icons/terminal-box-line.svg
  docs/assets/main-demo.gif
  git-workflow.md
Labels: enhancement, documentation, community

#640 Implement analytics collection
  .github/workflows/branch-build.yml
  .github/workflows/pr-build.yaml
  .gitignore
  .goreleaser.yml
  CONTRIBUTING.md
  cmd/botkube/main.go
  comm_config.yaml.tpl
  go.mod
  go.sum
  hack/goreleaser.sh
  helm/botkube/templates/analytics-config.yaml
  helm/botkube/templates/deployment.yaml
  helm/botkube/values.yaml
  internal/analytics/config.go
  internal/analytics/default_reporter.go
  internal/analytics/identity.go
  internal/analytics/logger_adapter.go
  internal/analytics/noop_reporter.go
  internal/analytics/reporter.go
  pkg/kube/client.go
  pkg/version/version.go
  resource_config.yaml.tpl
Labels: enhancement

#642 Hands free Helm Chart README.md
  .github/workflows/chart-testing.yaml
  .github/workflows/ci.yml
  Makefile
  hack/kind-cluster.sh
  hack/process-chart.sh
  helm/botkube/README.md
  helm/botkube/README.tpl.md
  helm/botkube/values.yaml
  helm/ct/README.md
  helm/ct/lint-cfg.yaml
  helm/ct/lint-rules.yaml
Labels: enhancement, helm-chart, ci

#645 Add automatic Go imports formatting
  .github/workflows/ci.yml
  .gitignore
  CONTRIBUTING.md
  Makefile
  cmd/botkube/main.go
  hack/fmt-imports.sh
  internal/analytics/default_reporter.go
  internal/analytics/identity.go
  test/e2e/slack_test.go
Labels: enhancement, ci

#644 Collect in-app usage analytics events
  .gitignore
  cmd/botkube/main.go
  go.mod
  go.sum
  helm/botkube/templates/deployment.yaml
  internal/analytics/anonymized_event.go
  internal/analytics/anonymized_event_test.go
  internal/analytics/export_test.go
  internal/analytics/fake_segment_cli_test.go
  internal/analytics/logger_adapter.go
  internal/analytics/noop_reporter.go
  internal/analytics/report_panic.go
  internal/analytics/report_panic_test.go
  internal/analytics/reporter.go
  internal/analytics/segment_logger_adapter.go
  internal/analytics/segment_reporter.go
  internal/analytics/segment_reporter_test.go
  internal/analytics/testdata/TestSegmentReporter_RegisterCurrentIdentity.json
  internal/analytics/testdata/TestSegmentReporter_ReportBotEnabled.json
  internal/analytics/testdata/TestSegmentReporter_ReportCommand.json
  internal/analytics/testdata/TestSegmentReporter_ReportFatalError/Identity.json
  internal/analytics/testdata/TestSegmentReporter_ReportFatalError/No_identity.json
  internal/analytics/testdata/TestSegmentReporter_ReportHandledEventError.json
  internal/analytics/testdata/TestSegmentReporter_ReportHandledEventSuccess.json
  internal/analytics/testdata/TestSegmentReporter_ReportSinkEnabled.json
  internal/analytics/testdata/analytics.yaml
  pkg/bot/bot.go
  pkg/bot/discord.go
  pkg/bot/mattermost.go
  pkg/bot/slack.go
  pkg/bot/teams.go
  pkg/config/config.go
  pkg/controller/controller.go
  pkg/events/events.go
  pkg/execute/executor.go
  pkg/execute/factory.go
  pkg/notify/discord.go
  pkg/notify/elasticsearch.go
  pkg/notify/mattermost.go
  pkg/notify/notify.go
  pkg/notify/slack.go
  pkg/notify/webhook.go
Labels: enhancement

#653 Add ability to set bot name for MS Teams
  comm_config.yaml.tpl
  helm/botkube/README.md
  helm/botkube/values.yaml
  pkg/bot/teams.go
  pkg/config/config.go
  pkg/controller/controller.go
  pkg/httpsrv/server.go
Labels: enhancement

#654 Get Go version from the go.mod file on CI
  .github/workflows/branch-build.yml
  .github/workflows/ci.yml
  .github/workflows/pr-build.yaml
Labels: enhancement, ci

#659 Update BotKube to load the new configuration syntax
  .github/workflows/branch-build.yml
  .github/workflows/pr-build.yaml
  CONTRIBUTING.md
  cmd/botkube/main.go
  comm_config.yaml.tpl
  docs/proposal/2022-06-14-configuration-bindings.md
  global_config.yaml.tpl
  go.mod
  go.sum
  helm/botkube/README.md
  helm/botkube/e2e-test-values.yaml
  helm/botkube/templates/_helpers.tpl
  helm/botkube/templates/communicationsecret.yaml
  helm/botkube/templates/deployment.yaml
  helm/botkube/templates/global-config.yaml
  helm/botkube/templates/ingress.yaml
  helm/botkube/templates/service.yaml
  helm/botkube/templates/sslcert.yaml
  helm/botkube/templates/tests/e2e-test.yaml
  helm/botkube/values.yaml
  pkg/bot/discord.go
  pkg/bot/mattermost.go
  pkg/bot/slack.go
  pkg/bot/teams.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/testdata/TestLoadConfigSuccess.golden.yaml
  pkg/config/testdata/TestLoadConfigSuccess/analytics.yaml
  pkg/config/testdata/TestLoadConfigSuccess/config-all.yaml
  pkg/config/testdata/TestLoadConfigSuccess/config-global.yaml
  pkg/config/testdata/TestLoadConfigSuccess/config-slack-override.yaml
  pkg/config/testdata/TestLoadConfigSuccess/config.golden.yaml
  pkg/config/testdata/TestLoadConfigSuccess/executors.yaml
  pkg/config/testdata/TestLoadedConfigValidation/empty-executors-communications.yaml
  pkg/config/testdata/TestLoadedConfigValidation/multiple-executors-communications.yaml
  pkg/config/testdata/config-all.yaml
  pkg/config/testdata/config-global.yaml
  pkg/config/testdata/config-slack-override.yaml
  pkg/config/validator.go
  pkg/controller/config_watcher.go
  pkg/controller/controller.go
  pkg/execute/executor.go
  pkg/execute/resource.go
  pkg/filterengine/with_all_filters.go
  pkg/multierror/multierror.go
  pkg/notifier/discord.go
  pkg/notifier/elasticsearch.go
  pkg/notifier/mattermost.go
  pkg/notifier/notify.go
  pkg/notifier/slack.go
  pkg/notifier/webhook.go
  resource_config.yaml.tpl
  test/e2e/slack_test.go
Labels: enhancement, refactor, breaking

#646 Add new code owner
  .github/CODEOWNERS
Labels: community

#661 Add ability to specify extra pod labels in helm chart
  CONTRIBUTING.md
  Makefile
  hack/goreleaser.sh
  helm/botkube/README.md
  helm/botkube/templates/deployment.yaml
  helm/botkube/values.yaml
Labels: enhancement

#665 Fix image labels, remove not working go report badge
  CONTRIBUTING.md
  README.md
  build/Dockerfile
  build/test.Dockerfile
Labels: enhancement

#662 Add ability to enable/disable notifications per bot
  cmd/botkube/main.go
  pkg/bot/bot.go
  pkg/bot/discord.go
  pkg/bot/discord_fmt.go
  pkg/bot/mattermost.go
  pkg/bot/mattermost_fmt.go
  pkg/bot/slack.go
  pkg/bot/slack_fmt.go
  pkg/bot/teams.go
  pkg/bot/teams_fmt.go
  pkg/bot/teams_notif.go
  pkg/bot/utils.go
  pkg/config/config.go
  pkg/controller/config_watcher.go
  pkg/controller/controller.go
  pkg/controller/message.go
  pkg/controller/notifier.go
  pkg/controller/upgrade.go
  pkg/execute/executor.go
  pkg/execute/factory.go
  pkg/execute/notifier.go
  pkg/execute/notifier_test.go
  pkg/format/codeblock.go
  pkg/format/codeblock_test.go
  pkg/format/msg.go
  pkg/format/short_msg.go
  pkg/format/short_msg_test.go
  pkg/notifier/discord.go
  pkg/notifier/mattermost.go
  pkg/notifier/notify.go
  pkg/notifier/slack.go
  pkg/sink/elasticsearch.go
  pkg/sink/types.go
  pkg/sink/webhook.go
  pkg/sink/webhook_test.go
  test/e2e/slack_test.go
Labels: enhancement, refactor

#664 Add support for namespace settings in `kubectl` executor
  .gitignore
  global_config.yaml.tpl
  go.mod
  go.sum
  helm/botkube/README.md
  helm/botkube/e2e-test-values.yaml
  helm/botkube/templates/tests/e2e-test.yaml
  helm/botkube/values.yaml
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/testdata/TestLoadConfigSuccess/config.golden.yaml
  pkg/config/testdata/TestLoadConfigSuccess/executors.yaml
  pkg/execute/executor.go
  pkg/execute/executor_test.go
  pkg/execute/factory.go
  pkg/execute/kubectl.go
  pkg/execute/kubectl_test.go
  pkg/filterengine/filters/namespace_checker.go
  pkg/filterengine/filters/namespace_checker_test.go
  test/e2e/slack_test.go
  test/e2e/slack_tester_test.go
Labels: enhancement
