Repository kubeshop/botkube, pull requests merged in 2023-02, with the labels that each got.

#962 Comment deprecated Slack configuration properties
  comm_config.yaml.tpl
  helm/botkube/README.md
  helm/botkube/values.yaml
  pkg/config/config.go
Labels: bug

#959 Validate alias commands and display builtin command aliases
  cmd/botkube/main.go
  helm/botkube/e2e-test-values.yaml
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/testdata/TestLoadedConfigValidationErrors/invalid-alias-command.yaml
  pkg/config/testdata/TestLoadedConfigValidationErrors/missing-alias-command.yaml
  pkg/config/validator.go
  pkg/execute/action.go
  pkg/execute/alias.go
  pkg/execute/alias/list.go
  pkg/execute/alias/list_test.go
  pkg/execute/alias_test.go
  pkg/execute/command/verb.go
  pkg/execute/config.go
  pkg/execute/exec.go
  pkg/execute/executor.go
  pkg/execute/feedback.go
  pkg/execute/filter.go
  pkg/execute/help.go
  pkg/execute/mapping.go
  pkg/execute/notifier.go
  pkg/execute/ping.go
  pkg/execute/source.go
  pkg/execute/sourcebinding.go
  pkg/execute/version.go
  test/e2e/bots_test.go
Labels: bug, enhancement

#964 Update golang.org/x/net lib to fix reported CVEs
  go.mod
  go.sum
Labels: enhancement

#966 Update prometheus message format
  internal/source/prometheus/source.go
Labels: enhancement

#967 Add SourceBindings built-in alias and fix filtering commands
  pkg/execute/action.go
  pkg/execute/alias.go
  pkg/execute/config.go
  pkg/execute/config_test.go
  pkg/execute/exec.go
  pkg/execute/exec_test.go
  pkg/execute/executor.go
  pkg/execute/executor_filter.go
  pkg/execute/executor_filter_test.go
  pkg/execute/filter.go
  pkg/execute/mapping.go
  pkg/execute/source.go
  pkg/execute/sourcebinding.go
Labels: bug, enhancement

#968 Use new format to download deps
  cmd/executor/gh/main.go
  cmd/executor/helm/README.md
  pkg/pluginx/bin.go
Labels: enhancement

#970 Fix alias validation and "Show Config" button in Help
  pkg/bot/interactive/help.go
  pkg/bot/interactive/testdata/TestInteractiveMessageToMarkdown/render_with_custom_headers_and_default_new_lines.golden.txt
  pkg/bot/interactive/testdata/TestInteractiveMessageToMarkdown/render_with_custom_new_lines_and_default_headers.golden.txt
  pkg/bot/interactive/testdata/TestInteractiveMessageToPlaintext.golden.txt
  pkg/config/config.go
  pkg/config/testdata/TestLoadedConfigValidationErrors/invalid-alias-command.yaml
  pkg/config/validator.go
Labels: bug

#963 Support include/exclude regexes for event and resource constraints
  global_config.yaml.tpl
  helm/botkube/README.md
  helm/botkube/values.yaml
  internal/source/registration.go
  internal/source/registration_test.go
  internal/source/router.go
  internal/source/router_test.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/testdata/TestLoadConfigSuccess/config-all.yaml
  pkg/config/testdata/TestLoadConfigSuccess/config.golden.yaml
  pkg/config/testdata/TestLoadConfigWithPlugins/config-all.yaml
  pkg/config/testdata/TestLoadedConfigValidationWarnings/executors-include-warning.yaml
  pkg/config/validator.go
  pkg/execute/kubectl/merger.go
  pkg/execute/kubectl/merger_test.go
  pkg/execute/kubectl_cmd_builder.go
  pkg/execute/kubectl_cmd_builder_test.go
  pkg/execute/kubectl_test.go
  pkg/recommendation/resource_events_test.go
Labels: enhancement, breaking

#980 Include API Key when fetching remote Botkube configuration
  cmd/botkube/main.go
  helm/botkube/README.md
  helm/botkube/templates/deployment.yaml
  helm/botkube/values.yaml
  internal/config/env_provider.go
  internal/config/gql_client.go
  internal/config/gql_client_test.go
  internal/config/gql_provider.go
  internal/config/gql_provider_test.go
  pkg/config/config.go
  pkg/config/config_test.go
Labels: enhancement

#982 Add interactive builder in kubectl plugin
  cmd/executor/echo/README.md
  cmd/executor/helm/README.md
  cmd/executor/kubectl/README.md
  cmd/executor/kubectl/main.go
  helm/botkube/README.md
  helm/botkube/e2e-test-values.yaml
  helm/botkube/values.yaml
  internal/executor/helm/config.go
  internal/executor/helm/executor.go
  internal/executor/kubectl/accessreview/review.go
  internal/executor/kubectl/builder/config.go
  internal/executor/kubectl/builder/deps.go
  internal/executor/kubectl/builder/kubectl.go
  internal/executor/kubectl/builder/kubectl_cmd_builder.go
  internal/executor/kubectl/builder/kubectl_dropdowns.go
  internal/executor/kubectl/builder/kubectl_test.go
  internal/executor/kubectl/builder/strings.go
  internal/executor/kubectl/config.go
  internal/executor/kubectl/executor.go
  internal/executor/kubectl/executor_test.go
  pkg/api/executor/executor.pb.go
  pkg/api/executor/grpc_adapter.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/testdata/TestLoadConfigSuccess/config.golden.yaml
  pkg/config/testdata/TestLoadedConfigValidationErrors/executors-default-ns.yaml
  pkg/config/validator.go
  pkg/execute/executor.go
  pkg/execute/fake_kc_guard_test.go
  pkg/execute/kubectl/fake_kc_guard.go
  pkg/execute/kubectl_cmd_builder_test.go
  pkg/execute/plugin_executor.go
  proto/executor.proto
  test/e2e/bots_test.go
Labels: enhancement
