Repository kubeshop/botkube, pull requests merged in 2023-06, with the labels that each got.

#1085 Handle --all-clusters flag
  pkg/execute/params.go
Labels: enhancement

#1087 Add Botkube illustration
  branding/logos/botkube-illustration-faces.svg
Labels: documentation

#1091 Send the cluster name for all interactive commands
  cmd/botkube/main.go
  internal/executor/kubectl/builder/kubectl.go
  pkg/api/message_bot_name.go
  pkg/bot/cloudslack.go
  pkg/execute/executor.go
  pkg/execute/plugin_executor.go
Labels: enhancement

#1090 Add cloudslack Audit to Platforms
  internal/remote/api.go
Labels: enhancement

#1096 Fix ServiceAccount token path in Config Watcher
  helm/botkube/README.md
  helm/botkube/templates/deployment.yaml
  helm/botkube/values.yaml
Labels: bug

#1095 Implement retries for Start Cloud Slack func
  cmd/botkube/main.go
  pkg/bot/cloudslack.go
  pkg/bot/cloudslack_test.go
Labels: enhancement

#1098 Make sure that `kubectl` uses a proper kubeconfig
  internal/executor/kubectl/builder/deps.go
  internal/executor/kubectl/builder/kubectl.go
  internal/executor/kubectl/builder/kubectl_test.go
  internal/executor/kubectl/executor.go
  internal/executor/kubectl/kc_runner.go
Labels: bug

#1108 Fix scheduling messages for Cloud Slack
  internal/source/scheduler.go
  pkg/bot/cloudslack.go
  pkg/bot/socketslack.go
Labels: bug
