Repository kubeshop/botkube, pull requests merged in 2023-01, with the labels that each got.

#905 Add commands for Sources and Executors
  internal/plugin/logger.go
  pkg/bot/discord.go
  pkg/bot/mattermost.go
  pkg/bot/socketslack.go
  pkg/bot/teams.go
  pkg/execute/command.go
  pkg/execute/command_test.go
  pkg/execute/exec.go
  pkg/execute/exec_test.go
  pkg/execute/executor.go
  pkg/execute/factory.go
  pkg/execute/source.go
  pkg/execute/source_test.go
  test/e2e/bots_test.go
Labels: enhancement

#911 Add plugins configuration to make release possible
  .github/workflows/process-chart.yml
  cmd/executor/helm/README.md
  helm/botkube/README.md
  helm/botkube/e2e-test-values.yaml
  helm/botkube/values.yaml
Labels: enhancement

#912 Add helm get and history cmds, update Botkube help, add testing scenario, fix bugs
  cmd/botkube/main.go
  cmd/executor/helm/README.md
  helm/botkube/e2e-test-values.yaml
  internal/executor/helm/bin_runner.go
  internal/executor/helm/commands.go
  internal/executor/helm/config.go
  internal/executor/helm/executor.go
  internal/executor/helm/get.go
  internal/executor/helm/history.go
  internal/executor/helm/list.go
  internal/executor/helm/status.go
  internal/executor/helm/test.go
  internal/executor/helm/version.go
  internal/plugin/manager.go
  pkg/bot/interactive/help.go
  pkg/bot/interactive/markdown_test.go
  pkg/bot/interactive/plaintext_test.go
  pkg/bot/interactive/plugin_help.go
  pkg/execute/executor.go
  pkg/execute/factory.go
  pkg/execute/help.go
  test/e2e/bots_test.go
Labels: enhancement

#910 Describe RBAC design proposal and add instruction for RBAC PoC
  docs/investigation/rbac/README.md
  docs/investigation/rbac/assets/clusterrole.yaml
  docs/investigation/rbac/assets/clusterrole2.yaml
  docs/investigation/rbac/assets/role.yaml
  docs/proposal/2022-12-23-rbac.md
Labels: documentation

#913 Replace removed 'list commands', print multi-cluster info only for supported platforms
  pkg/bot/interactive/help.go
  pkg/bot/interactive/testdata/TestInteractiveMessageToMarkdown/render_with_custom_headers_and_default_new_lines.golden.txt
  pkg/bot/interactive/testdata/TestInteractiveMessageToMarkdown/render_with_custom_new_lines_and_default_headers.golden.txt
  pkg/bot/interactive/testdata/TestInteractiveMessageToPlaintext.golden.txt
  pkg/execute/kubectl.go
  pkg/execute/kubectl_test.go
  test/e2e/bots_test.go
Labels: enhancement

#914 Remove support for running kubectl command without prefix
  pkg/bot/discord.go
  pkg/bot/interactive/help.go
  pkg/bot/interactive/testdata/TestInteractiveMessageToMarkdown/render_with_custom_headers_and_default_new_lines.golden.txt
  pkg/bot/interactive/testdata/TestInteractiveMessageToMarkdown/render_with_custom_new_lines_and_default_headers.golden.txt
  pkg/bot/interactive/testdata/TestInteractiveMessageToPlaintext.golden.txt
  pkg/execute/executor.go
  pkg/execute/kubectl.go
  pkg/execute/kubectl/checker.go
  pkg/execute/kubectl/merger.go
  pkg/execute/kubectl_test.go
  test/e2e/bots_test.go
Labels: breaking

#917 Add helm binding to all bot platforms
  helm/botkube/README.md
  helm/botkube/values.yaml
Labels: bug

#918 Print Display Name for `status sourcebindings`
  pkg/execute/sourcebinding.go
Labels: bug

#921 Add default helm namespace, update helm help
  internal/executor/helm/executor.go
  internal/executor/helm/executor_test.go
  internal/executor/helm/help.go
Labels: bug

#923 Fix marshalling event for Elasticsearch integration
  pkg/event/event.go
Labels: bug

#926 Cherry-pick bug fixes for 0.17
  internal/executor/helm/executor.go
  internal/executor/helm/executor_test.go
  internal/executor/helm/help.go
  pkg/event/event.go
Labels: bug

#928 Fix changelog generation
  .github/workflows/release.yml
Labels: bug

#924 start|stop -> enable|disable notifications
  internal/analytics/segment_reporter_test.go
  internal/analytics/testdata/TestSegmentReporter_ReportCommand.json
Labels: bug

#940 Fetch only used plugin repositories, fix logging, add repo validation
  internal/plugin/manager.go
  internal/plugin/manager_test.go
  internal/source/dispatcher.go
  pkg/bot/interactive/help.go
  pkg/config/config.go
  pkg/format/title.go
Labels: enhancement

#932 Add JSON schema to plugins
  cmd/executor/echo/main.go
  cmd/source/cm-watcher/main.go
  internal/executor/helm/executor.go
  internal/plugin/index.go
  internal/plugin/index_builder.go
  internal/plugin/store.go
  pkg/api/executor/executor.pb.go
  pkg/api/executor/grpc_adapter.go
  pkg/api/plugin.go
  pkg/api/source/grpc_adapter.go
  pkg/api/source/source.pb.go
  proto/executor.proto
  proto/source.proto
Labels: enhancement

#944 Upload plugins to GCS
  .github/workflows/branch-build.yml
  .github/workflows/pr-build.yaml
  .github/workflows/upload-plugins.yaml
Labels: enhancement

#942 Prometheus source plugin
  .goreleaser.plugin.yaml
  cmd/source/prometheus/main.go
  go.sum
  helm/botkube/README.md
  helm/botkube/values.yaml
  internal/source/prometheus/client.go
  internal/source/prometheus/config.go
  internal/source/prometheus/source.go
Labels: enhancement

#950 Support fetching plugin dependencies
  build/Dockerfile
  go.mod
  go.sum
  internal/executor/helm/bin_runner.go
  internal/executor/helm/executor.go
  internal/plugin/index.go
  internal/plugin/index_builder.go
  internal/plugin/index_test.go
  internal/plugin/manager.go
  internal/plugin/manager_test.go
  internal/plugin/store.go
  internal/plugin/store_test.go
  internal/plugin/testdata/TestNewStoreRepository/botkube.yaml
  internal/plugin/testdata/TestValidateIndexErrors/invalid.yaml
  internal/plugin/testdata/TestValidateIndexSuccess/valid.yaml
  pkg/api/executor/executor.pb.ext.go
  pkg/api/executor/executor.pb.go
  pkg/api/executor/grpc_adapter.go
  pkg/api/plugin.go
  pkg/api/source/grpc_adapter.go
  pkg/api/source/source.pb.ext.go
  pkg/api/source/source.pb.go
  proto/executor.proto
  proto/source.proto
Labels: enhancement

#952 Fix Prometheus source JSON schema and generated resources CI job
  .github/workflows/pr-build.yaml
  internal/source/prometheus/source.go
  pkg/api/executor/executor.pb.go
  pkg/api/source/source.pb.go
Labels: bug

#953 Add GitHub issue creator
  .goreleaser.plugin.yaml
  cmd/executor/gh/main.go
Labels: enhancement

#948 Support Help() in plugins
  cmd/executor/echo/main.go
  cmd/executor/gh/main.go
  internal/executor/helm/commands.go
  internal/executor/helm/executor.go
  internal/executor/helm/help.go
  pkg/api/executor/executor.pb.go
  pkg/api/executor/executor_grpc.pb.go
  pkg/api/executor/grpc_adapter.go
  pkg/execute/executor.go
  pkg/execute/plugin_executor.go
  proto/executor.proto
  test/e2e/bots_test.go
Labels: enhancement

#956 Support global aliases for commands
  helm/botkube/README.md
  helm/botkube/e2e-test-values.yaml
  helm/botkube/templates/global-config.yaml
  helm/botkube/values.yaml
  internal/plugin/manager.go
  internal/plugin/manager_test.go
  pkg/bot/interactive/help.go
  pkg/bot/interactive/markdown.go
  pkg/bot/interactive/testdata/TestInteractiveMessageToMarkdown/render_with_custom_headers_and_default_new_lines.golden.txt
  pkg/bot/interactive/testdata/TestInteractiveMessageToMarkdown/render_with_custom_new_lines_and_default_headers.golden.txt
  pkg/bot/interactive/testdata/TestInteractiveMessageToPlaintext.golden.txt
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/plugin.go
  pkg/config/testdata/TestLoadConfigSuccess/config.golden.yaml
  pkg/config/testdata/TestLoadedConfigValidationErrors/invalid-alias.yaml
  pkg/execute/action.go
  pkg/execute/alias.go
  pkg/execute/alias/expand.go
  pkg/execute/alias/expand_test.go
  pkg/execute/alias/for_executor.go
  pkg/execute/alias/for_executor_test.go
  pkg/execute/alias_test.go
  pkg/execute/config_test.go
  pkg/execute/exec.go
  pkg/execute/exec_test.go
  pkg/execute/executor.go
  pkg/execute/factory.go
  pkg/execute/kubectl.go
  pkg/execute/kubectl/commander.go
  pkg/execute/kubectl/guard.go
  pkg/execute/kubectl_cmd_builder.go
  pkg/execute/kubectl_cmd_builder_test.go
  pkg/execute/kubectl_test.go
  pkg/execute/mapping.go
  pkg/execute/params.go
  pkg/execute/plugin_executor.go
  pkg/execute/source.go
  pkg/execute/source_test.go
  pkg/filterengine/filterengine.go
  pkg/maputil/sort_keys.go
  pkg/maputil/sort_keys_test.go
  test/e2e/bots_test.go
Labels: enhancement
