Repository kubeshop/botkube, pull requests merged in 2023-11, with the labels that each got.

#1301 Simplify Teams gRPC contract, add support for gRPC auth
  pkg/api/cloudteams/cloud_teams.pb.go
  pkg/bot/teams_cloud.go
  pkg/bot/teams_cloud_grpc.go
  proto/cloud_teams.proto
Labels: enhancement

#1308 workflow dispatch
  .github/workflows/publish-chart.yml
Labels: ci

#1309 Fecth depth set for correct commit id
  .github/workflows/publish-chart.yml
Labels: other

#1307 Fix help message, send the core message over gRPC
  internal/executor/thread-mate/service.go
  internal/executor/x/output/message_parser.go
  internal/executor/x/output/message_tutorial.go
  pkg/api/cloudteams/cloud_teams.pb.go
  pkg/api/executor/grpc_adapter.go
  pkg/bot/interactive/plugin_help.go
  pkg/bot/teams_cloud.go
  pkg/config/config.go
  pkg/execute/plugin_executor.go
  pkg/formatx/space_table.go
  pkg/formatx/space_table_test.go
  pkg/mathx/int.go
  proto/cloud_teams.proto
Labels: enhancement

#1310 Reduce amount of anonymous analytics events
  cmd/botkube-agent/main.go
  go.mod
  internal/analytics/batched/data.go
  internal/analytics/batched/data_test.go
  internal/analytics/batched/heartbeat.go
  internal/analytics/export_test.go
  internal/analytics/noop_reporter.go
  internal/analytics/reporter.go
  internal/analytics/segment_reporter.go
  internal/analytics/segment_reporter_test.go
  internal/analytics/testdata/TestSegmentReporter_ReportHandledEventError.json
  internal/analytics/testdata/TestSegmentReporter_ReportHandledEventSuccess.json
  internal/analytics/testdata/TestSegmentReporter_ReportHeartbeatEvent.json
  internal/analytics/testdata/TestSegmentReporter_Run.json
Labels: enhancement

#1311 md formatter change
  pkg/bot/interactive/markdown.go
  pkg/bot/interactive/markdown_test.go
  pkg/bot/interactive/plaintext.go
Labels: enhancement

#1312 Fix audit logs and config persistence for Cloud Teams
  internal/audit/gql_reporter.go
  internal/audit/reporter.go
  internal/remote/api.go
  internal/remote/graphql/connected_platforms.go
  internal/remote/graphql/models_gen.go
  internal/remote/graphql/platforms.go
  internal/remote/graphql/usage.go
  internal/remote/platform.go
  internal/status/gql_reporter.go
  pkg/bot/teams_cloud.go
  pkg/config/manager.go
  pkg/config/manager_remote.go
  pkg/execute/executor.go
  pkg/execute/factory.go
  pkg/execute/mapping.go
Labels: bug

#1313 Add opt to use regex for json path values
  internal/source/github_events/json_matcher.go
  internal/source/github_events/jsonschema.json
Labels: enhancement

#1315 Release 1.6 rc.2
  internal/audit/gql_reporter.go
  internal/audit/reporter.go
  internal/remote/api.go
  internal/remote/graphql/connected_platforms.go
  internal/remote/graphql/models_gen.go
  internal/remote/graphql/platforms.go
  internal/remote/graphql/usage.go
  internal/remote/platform.go
  internal/source/github_events/json_matcher.go
  internal/source/github_events/jsonschema.json
  internal/status/gql_reporter.go
  pkg/bot/teams_cloud.go
  pkg/config/manager.go
  pkg/config/manager_remote.go
  pkg/execute/executor.go
  pkg/execute/factory.go
  pkg/execute/mapping.go
Labels: enhancement

#1314 Update Teams apps
  assets/ms-teams/Botkube.zip
  assets/ms-teams/BotkubeDev.zip
Labels: enhancement

#1316 Update Teams apps
  assets/ms-teams/Botkube.zip
  assets/ms-teams/BotkubeDev.zip
Labels: enhancement

#1320 Add documentationURL to plugins
  internal/executor/doctor/executor.go
  internal/executor/flux/executor.go
  internal/executor/helm/executor.go
  internal/executor/kubectl/executor.go
  internal/plugin/index.go
  internal/plugin/index_builder.go
  internal/plugin/store.go
  internal/source/argocd/argocd.go
  internal/source/github_events/source_grpc.go
  internal/source/keptn/source.go
  internal/source/kubernetes/source.go
  internal/source/prometheus/source.go
  pkg/api/executor/executor.pb.go
  pkg/api/executor/grpc_adapter.go
  pkg/api/plugin.go
  pkg/api/source/grpc_adapter.go
  pkg/api/source/source.pb.go
  proto/executor.proto
  proto/source.proto
Labels: enhancement

#1319 Additional logs for the grpc conn.
  pkg/bot/slack_cloud.go
  pkg/bot/teams_cloud.go
Labels: enhancement

#1323 updated docker to 24.0.7
  go.mod
  go.sum
Labels: other

#1322 Production smoke tests
  .github/workflows/prod-e2e-test.yml
  test/cloud-slack-dev-e2e/cloud_slack_dev_e2e_test.go
  test/helmx/helm_helpers.go
Labels: enhancement
