Repository kubeshop/botkube, pull requests merged in 2023-05, with the labels that each got.

#1054 Use namespace filter in Recommendations
  internal/source/kubernetes/router.go
  pkg/config/manager_remote.go
  test/e2e/bots_test.go
Labels: bug

#1060 use kubeconfig from exec input
  internal/executor/kubectl/executor.go
Labels: bug

#1062 use kubeconfig for gh plugin
  cmd/executor/gh/main.go
Labels: bug

#1061 Add logging when executing a command in not configured channel
  helm/botkube/README.md
  helm/botkube/values.yaml
  pkg/action/provider.go
  pkg/action/provider_test.go
  pkg/bot/discord.go
  pkg/bot/mattermost.go
  pkg/bot/slack.go
  pkg/bot/socketslack.go
  pkg/bot/teams.go
  pkg/execute/executor.go
  pkg/execute/factory.go
Labels: bug

#1063 Add validation that kubeconfig is specified
  cmd/executor/gh/main.go
  internal/executor/helm/executor.go
  internal/executor/helm/executor_test.go
  internal/executor/kubectl/executor.go
  internal/source/dispatcher.go
  internal/source/kubernetes/source.go
  pkg/api/source/grpc_adapter.go
  pkg/api/source/logger.go
  pkg/pluginx/kubeconfig.go
Labels: enhancement

#1069 Update plugin repo for release
  .github/workflows/process-chart.yml
  helm/botkube/README.md
  helm/botkube/values.yaml
Labels: bug, ci
