Repository kubeshop/botkube, pull requests merged in 2023-03, with the labels that each got.

#1004 Add resource version for status reporting and update configuration types
  cmd/botkube/main.go
  go.mod
  go.sum
  internal/audit/reporter.go
  internal/config/env_provider.go
  internal/config/env_provider_test.go
  internal/config/flag.go
  internal/config/fs_provider.go
  internal/config/fs_provider_test.go
  internal/config/gql_client.go
  internal/config/gql_client_test.go
  internal/config/gql_provider.go
  internal/config/gql_provider_test.go
  internal/config/provider.go
  internal/config/provider_test.go
  internal/config/testdata/TestGetProvider/all.yaml
  internal/config/testdata/TestGetProvider/first.yaml
  internal/config/testdata/TestGetProvider/from-cli-flag-second.yaml
  internal/config/testdata/TestGetProvider/from-cli-flag.yaml
  internal/config/testdata/TestGetProvider/second.yaml
  internal/config/testdata/TestGetProvider/third.yaml
  internal/config/testdata/gql_get_deployment_success.json
  internal/config/updater.go
  internal/executor/kubectl/config.go
  internal/graphql/client.go
  internal/loggerx/logger.go
  internal/plugin/logger.go
  internal/source/kubernetes/source.go
  internal/source/prometheus/source.go
  internal/source/scheduler_test.go
  internal/status/gql_reporter.go
  internal/status/noop_reporter.go
  internal/status/reporter.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/provider.go
  pkg/config/testdata/TestLoadConfigSuccess/config.golden.yaml
  pkg/controller/controller.go
  pkg/controller/upgrade.go
Labels: enhancement

#1014 Enable actions even if not bind to a specific channel
  go.mod
  go.sum
  helm/botkube/e2e-test-values.yaml
  internal/executor/kubectl/config.go
  internal/plugin/collector.go
  internal/source/kubernetes/event/anonymized_event.go
  internal/source/scheduler.go
  pkg/config/manager.go
  pkg/execute/kubectl_cmd_builder.go
  pkg/maputil/sort_keys.go
  test/e2e/bots_test.go
  test/e2e/k8s_helpers_test.go
Labels: bug

#1013 Update and validate plugin JSON schemas, produce second plugin index
  .github/workflows/upload-plugins.yaml
  .gitignore
  .goreleaser.yml
  Makefile
  cmd/executor/echo/main.go
  cmd/source/cm-watcher/main.go
  global_config.yaml.tpl
  go.mod
  go.sum
  hack/gen-plugin-index.go
  helm/botkube/README.md
  helm/botkube/templates/global-config.yaml
  helm/botkube/templates/persistent-config.yaml
  helm/botkube/values.yaml
  internal/executor/helm/executor.go
  internal/executor/kubectl/config.go
  internal/executor/kubectl/executor.go
  internal/plugin/index_builder.go
  internal/plugin/index_builder_test.go
  internal/source/kubernetes/config/config.go
  internal/source/kubernetes/filterengine/with_all_filters.go
  internal/source/kubernetes/source.go
  internal/source/prometheus/config.go
  internal/source/prometheus/source.go
  pkg/config/config.go
  pkg/config/manager_test.go
  pkg/config/state.go
  pkg/config/testdata/TestLoadConfigSuccess/config.golden.yaml
  pkg/execute/config_test.go
  test/fake/plugin_server.go
Labels: enhancement

#1019 Report Deployment ID when using remote configuration
  cmd/botkube/main.go
  internal/analytics/identity.go
  internal/analytics/noop_reporter.go
  internal/analytics/reporter.go
  internal/analytics/segment_reporter.go
  internal/analytics/segment_reporter_test.go
  internal/analytics/testdata/TestSegmentReporter_RegisterCurrentIdentity.json
Labels: enhancement

#1022 Fix audit log reporting for source events and commands
  cmd/botkube/main.go
  internal/analytics/segment_reporter.go
  internal/audit/gql_reporter.go
  internal/audit/reporter.go
  internal/config/remote/gql_client.go
  internal/heartbeat/gql_reporter.go
  internal/remote/api.go
  internal/source/dispatcher.go
  internal/source/scheduler.go
  internal/status/gql_reporter.go
  pkg/action/provider.go
  pkg/action/provider_test.go
  pkg/bot/bot.go
  pkg/bot/discord.go
  pkg/bot/mattermost.go
  pkg/bot/slack.go
  pkg/bot/socketslack.go
  pkg/bot/teams.go
  pkg/config/manager.go
  pkg/config/manager_remote.go
  pkg/execute/executor.go
  pkg/execute/factory.go
  pkg/execute/mapping.go
  pkg/execute/sourcebinding.go
  pkg/execute/sourcebinding_test.go
  pkg/ptr/ptr.go
Labels: bug

#1023 Support ChannelName RBAC mapping for executors
  helm/botkube/README.md
  helm/botkube/templates/clusterrolebinding.yaml
  helm/botkube/values.yaml
  internal/plugin/kubeconfig.go
  pkg/execute/plugin_executor.go
Labels: enhancement

#1026 Remove built-in kubectl, filters, defaultNamespace, fix list bugs
  .gitignore
  CONTRIBUTING.md
  build/Dockerfile
  cmd/botkube/main.go
  comm_config.yaml.tpl
  global_config.yaml.tpl
  helm/botkube/README.md
  helm/botkube/e2e-test-values.yaml
  helm/botkube/values.yaml
  internal/executor/helm/executor.go
  internal/executor/kubectl/executor.go
  internal/plugin/kubeconfig.go
  internal/source/dispatcher.go
  pkg/bot/interactive/help.go
  pkg/bot/interactive/markdown_test.go
  pkg/bot/interactive/plaintext_test.go
  pkg/bot/interactive/plugin_help.go
  pkg/bot/interactive/testdata/TestInteractiveMessageToMarkdown/render_with_custom_headers_and_default_new_lines.golden.txt
  pkg/bot/interactive/testdata/TestInteractiveMessageToMarkdown/render_with_custom_new_lines_and_default_headers.golden.txt
  pkg/bot/interactive/testdata/TestInteractiveMessageToPlaintext.golden.txt
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/testdata/TestLoadConfigSuccess/_aaa-special-file.yaml
  pkg/config/testdata/TestLoadConfigSuccess/actions.yaml
  pkg/config/testdata/TestLoadConfigSuccess/config-all.yaml
  pkg/config/testdata/TestLoadConfigSuccess/config.golden.yaml
  pkg/config/testdata/TestLoadConfigSuccess/executors.yaml
  pkg/config/testdata/TestLoadConfigWithPlugins/config-all.yaml
  pkg/config/testdata/TestLoadedConfigValidationErrors/missing-alias-command.yaml
  pkg/config/testdata/TestLoadedConfigValidationWarnings/executors-include-warning.yaml
  pkg/config/validator.go
  pkg/execute/alias_test.go
  pkg/execute/default_runner.go
  pkg/execute/exec.go
  pkg/execute/exec_test.go
  pkg/execute/executor.go
  pkg/execute/factory.go
  pkg/execute/kubectl.go
  pkg/execute/kubectl/checker.go
  pkg/execute/kubectl/checker_test.go
  pkg/execute/kubectl/commander.go
  pkg/execute/kubectl/commander_test.go
  pkg/execute/kubectl/helpers_test.go
  pkg/execute/kubectl/merger.go
  pkg/execute/kubectl/merger_test.go
  pkg/execute/kubectl/resource-normalizer.go
  pkg/execute/kubectl_cmd_builder.go
  pkg/execute/kubectl_cmd_builder_msg.go
  pkg/execute/kubectl_cmd_builder_test.go
  pkg/execute/kubectl_test.go
  pkg/execute/mapping.go
  pkg/execute/plugin_discovery.go
  pkg/execute/source.go
  pkg/execute/source_test.go
  test/e2e/bots_test.go
  test/e2e/slack_driver_test.go
Labels: enhancement, breaking

#1031 Fix logging heartbeat error and require providing Prometheus URL
  internal/insights/k8s_collector.go
  internal/source/prometheus/config.go
  internal/source/prometheus/source.go
  pkg/api/source/grpc_adapter.go
Labels: bug
