Repository kubeshop/botkube, pull requests merged in 2023-07, with the labels that each got.

#1118 Streamline the help message
  go.mod
  go.sum
  internal/executor/kubectl/builder/kubectl_dropdowns.go
  pkg/api/message.go
  pkg/bot/interactive/help.go
  pkg/bot/interactive/markdown.go
  pkg/bot/interactive/plugin_help.go
  pkg/bot/interactive/testdata/TestInteractiveMessageToMarkdown/render_with_custom_headers_and_default_new_lines.golden.txt
  pkg/bot/interactive/testdata/TestInteractiveMessageToMarkdown/render_with_custom_new_lines_and_default_headers.golden.txt
  pkg/bot/interactive/testdata/TestInteractiveMessageToPlaintext.golden.txt
  pkg/bot/slack_renderer.go
Labels: enhancement

#1112 Add initial version for install and run binaries
  .goreleaser.plugin.yaml
  CONTRIBUTING.md
  build/Dockerfile
  cmd/executor/gh/main.go
  cmd/executor/x/main.go
  cmd/executor/x/templates/argo.yaml
  cmd/executor/x/templates/flux.yaml
  cmd/executor/x/templates/helm.yaml
  go.mod
  go.sum
  hack/goreleaser.sh
  internal/executor/helm/executor.go
  internal/executor/helm/executor_test.go
  internal/executor/kubectl/executor_test.go
  internal/executor/kubectl/kc_runner.go
  internal/executor/kubectl/kc_runner_test.go
  internal/executor/x/cmd_parse.go
  internal/executor/x/cmd_parse_test.go
  internal/executor/x/config.go
  internal/executor/x/getter/download.go
  internal/executor/x/getter/getter.go
  internal/executor/x/getter/load.go
  internal/executor/x/getter/walk.go
  internal/executor/x/mathx/int.go
  internal/executor/x/output/helpers.go
  internal/executor/x/output/message_parser.go
  internal/executor/x/parser/space_table.go
  internal/executor/x/parser/space_table_test.go
  internal/executor/x/renderer.go
  internal/executor/x/run.go
  internal/executor/x/state/slack.go
  internal/executor/x/template/config.go
  internal/plugin/tmp_dir.go
  pkg/pluginx/command.go
  pkg/pluginx/command_opts.go
  pkg/pluginx/example_test.go
Labels: enhancement, breaking

#1121 Replace uuid with static value for Botkube SA
  helm/botkube/README.md
  helm/botkube/templates/_helpers.tpl
  helm/botkube/templates/deployment.yaml
  helm/botkube/values.yaml
Labels: bug

#1122 Fix event update logic for Kubernetes source
  helm/botkube/e2e-test-values.yaml
  internal/source/kubernetes/k8sutil/diff.go
  internal/source/kubernetes/k8sutil/diff_test.go
  internal/source/kubernetes/registration.go
  test/e2e/bots_test.go
Labels: bug

#1124 Revert API changes for api.Message
  internal/executor/kubectl/builder/kubectl_dropdowns.go
  internal/executor/x/output/message_parser.go
  pkg/api/message.go
  pkg/bot/interactive/help.go
  pkg/bot/interactive/plugin_help.go
  pkg/bot/slack_renderer.go
Labels: bug

#1117 Add wrap message template for x plugin
  .github/workflows/process-chart.yml
  Makefile
  cmd/executor/x/main.go
  cmd/executor/x/templates/flux.yaml
  helm/botkube/README.md
  helm/botkube/values.yaml
  internal/executor/x/output/message_wrapper.go
  internal/executor/x/run.go
  internal/executor/x/template/config.go
Labels: enhancement

#1129 Fix x plugin schema definition
  cmd/executor/x/main.go
Labels: bug

#1131 Add CLI command to generate cobra docs
  .github/workflows/pr-build.yaml
  Makefile
  cmd/cli/cmd/docs.go
  cmd/cli/cmd/root.go
  cmd/cli/docs/botkube.md
  cmd/cli/docs/botkube_login.md
  cmd/cli/docs/botkube_migrate.md
  go.mod
  go.sum
  internal/cli/frontmatter/format.go
Labels: enhancement

#1132 Remove duplicated ptr pkg
  .github/workflows/pr-build.yaml
  go.mod
  go.sum
  internal/httpx/http_client.go
  internal/plugin/manager.go
  internal/source/kubernetes/config/config.go
  internal/source/kubernetes/recommendation/factory.go
  internal/source/kubernetes/recommendation/factory_test.go
  internal/source/kubernetes/recommendation/resource_events.go
  internal/source/kubernetes/recommendation/resource_events_test.go
  internal/source/prometheus/config.go
  pkg/ptr/ptr.go
Labels: bug

#1127 Add tutorial message template for x plugin
  cmd/executor/x/main.go
  cmd/executor/x/templates/argo.yaml
  cmd/executor/x/templates/flux.yaml
  cmd/executor/x/templates/helm.yaml
  internal/executor/x/getter/load.go
  internal/executor/x/mathx/int.go
  internal/executor/x/output/message_tutorial.go
  internal/executor/x/run.go
  internal/executor/x/run_test.go
  internal/executor/x/template/config.go
  internal/executor/x/testdata/TestRunnerNoExecuteTemplate/helm.yaml
Labels: enhancement

#1136 Add Slack notifications for E2E tests
  .github/workflows/branch-build.yml
Labels: ci

#1134 Add option to install Botkube via CLI, add `--verbose` flag
  cmd/cli/cmd/install.go
  cmd/cli/cmd/migrate.go
  cmd/cli/cmd/root.go
  cmd/cli/docs/botkube.md
  cmd/cli/docs/botkube_install.md
  cmd/cli/docs/botkube_login.md
  cmd/cli/docs/botkube_migrate.md
  cmd/cli/docs/botkube_version.md
  go.mod
  go.sum
  internal/cli/install/config.go
  internal/cli/install/helm/config.go
  internal/cli/install/helm/install.go
  internal/cli/install/helm/status.go
  internal/cli/install/helm/version.go
  internal/cli/install/install.go
  internal/cli/install/iox/stdout.go
  internal/cli/migrate/migrate.go
  internal/cli/migrate/opts.go
  internal/cli/printer/status.go
  internal/cli/verbose.go
  internal/cli/verbose_test.go
  internal/kubex/config.go
Labels: enhancement

#1138 Fix migration test flag
  test/e2e/migration_test.go
Labels: bug, ci

#1140 Add logs streaming for `botkube install` command
  cmd/botkube-agent/main.go
  cmd/cli/cmd/install.go
  cmd/cli/docs/botkube_install.md
  go.mod
  go.sum
  helm/botkube/README.md
  helm/botkube/values.yaml
  internal/cli/install/config.go
  internal/cli/install/helm/config.go
  internal/cli/install/helm/install.go
  internal/cli/install/helm/status.go
  internal/cli/install/install.go
  internal/cli/install/logs/json_parser.go
  internal/cli/install/logs/k8s.go
  internal/cli/install/logs/printer.go
  internal/cli/printer/status.go
  internal/kubex/wait.go
  internal/loggerx/logger.go
  pkg/config/config.go
  pkg/config/testdata/TestLoadConfigSuccess/config.golden.yaml
  pkg/execute/config_test.go
Labels: enhancement

#1141 Add botkube uninstall command
  cmd/cli/cmd/install.go
  cmd/cli/cmd/root.go
  cmd/cli/cmd/uninstall.go
  cmd/cli/docs/botkube.md
  cmd/cli/docs/botkube_install.md
  cmd/cli/docs/botkube_uninstall.md
  internal/cli/helmx/action_cfg.go
  internal/cli/install/helm/config.go
  internal/cli/install/helm/install.go
  internal/cli/install/install.go
  internal/cli/printer/status.go
  internal/cli/uninstall/config.go
  internal/cli/uninstall/helm/config.go
  internal/cli/uninstall/helm/uninstall.go
  internal/cli/uninstall/uninstall.go
Labels: enhancement

#1142 Normalize and validate channel names and IDs
  internal/config/reloader/remote_test.go
  pkg/bot/cloudslack.go
  pkg/bot/discord.go
  pkg/bot/mattermost.go
  pkg/bot/slack.go
  pkg/bot/slack_utils.go
  pkg/bot/socketslack.go
  pkg/config/config_test.go
  pkg/config/testdata/TestLoadedConfigValidationErrors/invalid-channels.yaml
  pkg/config/validator.go
  pkg/conversation/normalize.go
  pkg/conversation/normalize_test.go
Labels: enhancement

#1146 Add build flags to CLI
  .goreleaser.yml
Labels: bug

#1147 Plugins logger respect generic logger settings
  cmd/botkube-agent/main.go
  internal/cli/install/logs/json_parser.go
  internal/plugin/index_builder.go
  internal/plugin/logger.go
  internal/plugin/manager.go
  internal/plugin/manager_test.go
Labels: bug

#1150 Remove custom install for brew formula, fix Helm plugin formatting
  .goreleaser.yml
  internal/executor/helm/executor.go
  internal/executor/helm/executor_test.go
  internal/executor/helm/testdata/TestExecutorHelmInstallHelp.txt
Labels: bug

#1153 chore: pkg imported more than once
  internal/cli/install/logs/printer.go
Labels: refactor

#1159 Lint migration test
  .golangci.yml
  hack/fmt-imports.sh
  test/commplatform/discord_tester.go
  test/commplatform/slack_tester.go
  test/e2e/bots_test.go
  test/e2e/k8s_helpers_test.go
  test/e2e/migration_test.go
Labels: bug

#1157 Fix panics in Kubernetes plugin
  internal/source/kubernetes/registration.go
  internal/source/kubernetes/router.go
  test/e2e/migration_test.go
Labels: bug

#1156 Add reactions to Slack messages
  pkg/bot/slack_cloud.go
  pkg/bot/slack_cloud_test.go
  pkg/bot/slack_legacy.go
  pkg/bot/slack_legacy_test.go
  pkg/bot/slack_msg_tracker.go
  pkg/bot/slack_shared.go
  pkg/bot/slack_socket.go
  pkg/bot/slack_socket_test.go
Labels: enhancement

#1154 add human friendly error messages
  pkg/bot/discord.go
  pkg/bot/slack_shared.go
  pkg/bot/slack_socket.go
Labels: enhancement

#1161 fix doctor plugin schema
  cmd/executor/helm/README.md
  internal/executor/doctor/executor.go
  test/helpers/plugin_server.go
Labels: bug

#1165 Add tpl approach for plugin GoReleaser config
  .github/workflows/pr-build.yaml
  .goreleaser.plugin.tpl.yaml
  .goreleaser.plugin.yaml
  Makefile
  hack/gen-plugin-index.go
  hack/target/gen-goreleaser/main.go
  test/helpers/plugin_server.go
Labels: enhancement

#1163 Mattermost Enhancements
  .golangci.yml
  cmd/botkube-agent/main.go
  go.mod
  go.sum
  pkg/bot/mattermost.go
  pkg/bot/mattermost_render.go
Labels: bug

#1168 Trim suffix for Mattermost URL
  pkg/bot/mattermost.go
Labels: bug
