Repository kubeshop/botkube, pull requests merged in 2023-08, with the labels that each got.

#1170 Add flux executor plugin with GitHub support
  .goreleaser.plugin.yaml
  Makefile
  cmd/botkube-agent/main.go
  cmd/executor/flux/main.go
  go.mod
  go.sum
  internal/cli/config/config.go
  internal/cli/login/login.go
  internal/cli/migrate/migrate.go
  internal/executor/doctor/executor.go
  internal/executor/flux/commands.go
  internal/executor/flux/commands/store/tables.yaml
  internal/executor/flux/commands/store/tutorial.yaml
  internal/executor/flux/commands/template.go
  internal/executor/flux/config.go
  internal/executor/flux/diff_cmd.go
  internal/executor/flux/diff_ks_cmd.go
  internal/executor/flux/diff_ks_cmd_test.go
  internal/executor/flux/executor.go
  internal/executor/flux/forbidden.go
  internal/executor/flux/gh_cmd.go
  internal/executor/x/cmd_parse.go
  internal/executor/x/output/message_parser.go
  internal/executor/x/output/message_tutorial.go
  internal/executor/x/run.go
  internal/httpx/http_client.go
  internal/httpx/server.go
  internal/lifecycle/server.go
  internal/plugin/kubeconfig.go
  internal/source/dispatcher.go
  pkg/bot/teams.go
  pkg/controller/upgrade.go
  pkg/execute/plugin_executor.go
  pkg/pluginx/command.go
  pkg/pluginx/command_opts.go
Labels: enhancement

#1174 Add basic GitHub event source
  .gitignore
  .goreleaser.plugin.tpl.yaml
  .goreleaser.plugin.yaml
  Makefile
  cmd/executor/gh/main.go
  cmd/source/github-events/main.go
  go.mod
  go.sum
  internal/executor/flux/executor.go
  internal/httpx/canonical.go
  internal/httpx/canonical_test.go
  internal/source/github_events/config.go
  internal/source/github_events/event_types.go
  internal/source/github_events/gh/client.go
  internal/source/github_events/github_events.go
  internal/source/github_events/json_matcher.go
  internal/source/github_events/jsonschema.json
  internal/source/github_events/pr_matcher.go
  internal/source/github_events/render_opts.go
  internal/source/github_events/source_grpc.go
  internal/source/github_events/templates/templates.go
  internal/source/github_events/templates/testdata/payload.json
Labels: enhancement

#1176 platform async message handling
  go.mod
  go.sum
  pkg/bot/bot.go
  pkg/bot/discord.go
  pkg/bot/mattermost.go
  pkg/bot/slack_cloud.go
  pkg/bot/slack_legacy.go
  pkg/bot/slack_socket.go
Labels: bug

#1179 Refresh GraphQL types, add missing `flux` definition
  helm/botkube/README.md
  helm/botkube/values.yaml
  internal/remote/graphql/models_gen.go
  internal/remote/graphql/platforms.go
  internal/remote/graphql/usage.go
Labels: bug

#1182 Fix counting plugins migrated, Doctor JSON schema and multi-word command verbs reporting
  go.mod
  go.sum
  internal/cli/migrate/migrate.go
  internal/executor/doctor/executor.go
  pkg/bot/slack_socket.go
  pkg/execute/plugin_executor.go
  pkg/execute/plugin_executor_test.go
Labels: bug

#1184 Improve JSON schema for keptn, include Flux plugin in build, fix plugin count
  Makefile
  helm/botkube/README.md
  helm/botkube/values.yaml
  internal/cli/migrate/migrate.go
  internal/source/keptn/source.go
Labels: bug

#1185 Improve gh jsonschema, fix gh watch loop, allow watching all prs events
  internal/source/github_events/config.go
  internal/source/github_events/event_types.go
  internal/source/github_events/github_events.go
  internal/source/github_events/jsonschema.json
  internal/source/github_events/templates/templates.go
Labels: enhancement

#1186 Add flux under default executors
  helm/botkube/README.md
  helm/botkube/values.yaml
  internal/source/github_events/github_events.go
Labels: enhancement

#1194 Handle K8s empty resource list for K8s 1.26+
  internal/command/guard.go
  internal/command/guard_test.go
Labels: bug

#1197 Clean up grpc
  cmd/executor/echo/main.go
  cmd/executor/gh/main.go
  cmd/source/cm-watcher/main.go
  hack/gen-grpc-resources.sh
  internal/executor/helm/executor_test.go
  internal/source/dispatcher.go
  internal/source/kubernetes/event/event.go
  pkg/api/cloudslack/cloudslack.pb.go
  pkg/api/cloudslack/cloudslack_grpc.pb.go
  pkg/api/executor/executor.pb.go
  pkg/api/executor/executor_grpc.pb.go
  pkg/api/executor/grpc_adapter.go
  pkg/api/source/grpc_adapter.go
  pkg/api/source/source.pb.go
  pkg/api/source/source_grpc.pb.go
  pkg/execute/plugin_executor.go
  proto/executor.proto
  proto/source.proto
Labels: breaking

#1202 Add support for archived plugins
  .github/actions/dump-cluster/action.yaml
  .github/workflows/branch-build.yml
  .github/workflows/pr-build.yaml
  .github/workflows/release.yml
  .github/workflows/upload-plugins.yaml
  .goreleaser.plugin.tpl.yaml
  .goreleaser.plugin.yaml
  .goreleaser.yml
  Makefile
  hack/gen-plugin-index.go
  hack/goreleaser.sh
  hack/target/build-plugins/main.go
  internal/plugin/downloader.go
  internal/plugin/downloader_test.go
  internal/plugin/index_builder.go
  internal/plugin/manager.go
  internal/plugin/store.go
  internal/plugin/testdata/TestGetFirstFileInDirectory/hidden_and_exe_files/._DS_Store
  internal/plugin/testdata/TestGetFirstFileInDirectory/hidden_and_exe_files/anotherfile.txt
  internal/plugin/testdata/TestGetFirstFileInDirectory/hidden_and_exe_files/test.exe
  internal/plugin/testdata/TestGetFirstFileInDirectory/no_valid_file/file.md
  internal/plugin/testdata/TestGetFirstFileInDirectory/no_valid_file/file.txt
  internal/plugin/testdata/TestGetFirstFileInDirectory/valid_file/example_bin
  internal/plugin/testdata/TestGetFirstFileInDirectory/valid_file/otherfile.md
  internal/plugin/testdata/TestGetFirstFileInDirectory/valid_file/testfile.txt
  internal/plugin/testdata/TestGetFirstFileInDirectory/valid_script/otherfile.md
  internal/plugin/testdata/TestGetFirstFileInDirectory/valid_script/script.sh
  internal/plugin/testdata/TestGetFirstFileInDirectory/valid_script/testfile.txt
  test/README.md
  test/fake/plugin_server.go
Labels: enhancement

#1206 Add JSON schema for GitHub reporter plugin
  cmd/executor/gh/main.go
Labels: enhancement

#1210 Introduce environment variables for Cloud Slack E2E tests
  .github/workflows/pr-build.yaml
Labels: ci

#1213 Remove Slack bot user name from CI by default
  .github/workflows/branch-build.yml
  .github/workflows/pr-build.yaml
  test/commplatform/slack_tester.go
Labels: bug, ci

#1207 Support bot accounts for Mattermost
  pkg/bot/mattermost.go
Labels: enhancement

#1214 Add fallback strategy to get MM team
  pkg/bot/mattermost.go
Labels: enhancement

#1208 Add config get CLI command
  cmd/cli/cmd/config/config.go
  cmd/cli/cmd/config/get.go
  cmd/cli/cmd/install.go
  cmd/cli/cmd/migrate.go
  cmd/cli/cmd/root.go
  cmd/cli/cmd/uninstall.go
  cmd/cli/docs/botkube.md
  cmd/cli/docs/botkube_config.md
  cmd/cli/docs/botkube_config_get.md
  cmd/cli/docs/botkube_migrate.md
  cmd/config-exporter/main.go
  go.mod
  internal/cli/config.go
  internal/cli/config/get.go
  internal/cli/install/install.go
  internal/cli/login/login.go
  internal/cli/migrate/migrate.go
  internal/cli/migrate/opts.go
  internal/cli/printer/format.go
  internal/cli/printer/json.go
  internal/cli/printer/resource.go
  internal/cli/printer/yaml.go
Labels: enhancement

#1219 Add GitHub action to enforce labels
  .github/workflows/enforce-labels.yml
Labels: enhancement, ci

#1221 Fix downloader for non archived plugins
  Makefile
  hack/target/build-plugins/main.go
  internal/plugin/downloader.go
  test/fake/plugin_server.go
Labels: bug
