Repository kubeshop/botkube, pull requests merged in 2023-09, with the labels that each got.

#1218 Ignore error-like GKE node maintenance events
  helm/botkube/README.md
  helm/botkube/values.yaml
Labels: enhancement

#1223 Update Readme with the latest GIF and content
  README.md
  docs/assets/icons/bug-line.svg
  docs/assets/icons/cloud-line.svg
  docs/assets/icons/question-answer-line.svg
  docs/assets/icons/stack-line.svg
  docs/assets/icons/terminal-box-line.svg
  docs/assets/main-demo.gif
Labels: documentation

#1226 Fix printing steps when file redirect is used
  cmd/cli/cmd/config/get.go
  cmd/cli/cmd/migrate.go
  internal/cli/config/get.go
  internal/cli/install/iox/stdout.go
  internal/cli/printer/dynamic_spinner.go
  internal/cli/printer/status.go
Labels: bug

#1220 Introduce interactive ArgoCD source plugin
  .goreleaser.plugin.yaml
  Makefile
  cmd/source/argocd/main.go
  go.mod
  go.sum
  helm/botkube/README.md
  helm/botkube/templates/clusterrole.yaml
  helm/botkube/templates/clusterrolebinding.yaml
  helm/botkube/templates/global-config.yaml
  helm/botkube/templates/rbac-groups.yaml
  helm/botkube/values.yaml
  internal/executor/helm/executor_test.go
  internal/executor/helm/testdata/TestExecutorHelmInstallHelp.txt
  internal/source/argocd/argocd.go
  internal/source/argocd/config-jsonschema.json
  internal/source/argocd/config.go
  internal/source/argocd/incoming_req.go
  internal/source/argocd/render.go
  internal/source/argocd/req-jsonschema.json
  internal/source/argocd/setup_notifications.go
  internal/source/dispatcher.go
  internal/source/github_events/source_grpc.go
  internal/source/incoming_webhook.go
  internal/source/kubernetes/k8sutil/resource.go
  internal/source/scheduler.go
  pkg/api/message.go
  pkg/api/source/grpc_adapter.go
  pkg/api/source/source.pb.go
  pkg/bot/teams.go
  pkg/config/config.go
  pkg/config/testdata/TestLoadConfigSuccess/config.golden.yaml
  pkg/execute/config_test.go
  proto/source.proto
Labels: enhancement

#1225 Fix schemas for gh-events and flux, fix render in gh-events
  internal/executor/flux/executor.go
  internal/executor/flux/jsonschema.json
  internal/source/github_events/github_events.go
  internal/source/github_events/jsonschema.json
  internal/source/github_events/render_opts.go
Labels: bug

#1227 Improve e2e perf
  .github/workflows/pr-build.yaml
  .gitignore
  .goreleaser.yml
  hack/goreleaser.sh
Labels: enhancement, ci

#1233 Fix PR build workflow indentation
  .github/workflows/pr-build.yaml
Labels: ci

#1228 Improve non-interactive messages for ArgoCD source
  helm/botkube/README.md
  helm/botkube/templates/clusterrole.yaml
  helm/botkube/values.yaml
  internal/plugin/manager.go
  internal/source/argocd/argocd.go
  internal/source/argocd/config.go
  internal/source/argocd/default-config.yaml
  internal/source/argocd/incoming_req.go
  internal/source/argocd/setup_notifications.go
  pkg/bot/teams_renderer.go
Labels: enhancement

#1232 Support custom OpenAI API params for Doctor plugin
  internal/executor/doctor/executor.go
Labels: enhancement

#1231 Fix help flag error, remove color codes
  internal/executor/flux/commands.go
  internal/executor/flux/executor.go
  internal/executor/flux/forbidden.go
  pkg/pluginx/command.go
  pkg/pluginx/command_opts.go
Labels: bug

#1234 Fix JSON schema for ArgoCD source plugin and spelling for CLI docs
  cmd/cli/cmd/install.go
  cmd/cli/cmd/uninstall.go
  cmd/cli/docs/botkube_install.md
  cmd/cli/docs/botkube_uninstall.md
  internal/source/argocd/config-jsonschema.json
Labels: bug, documentation

#1237 Fix ArgoCD notification setup and JSON schema
  .golangci.yml
  internal/plugin/kubeconfig.go
  internal/source/argocd/argocd.go
  internal/source/argocd/config-jsonschema.json
  internal/source/argocd/default-config.yaml
  internal/source/argocd/req-jsonschema.json
  internal/source/argocd/setup_notifications.go
  internal/source/argocd/setup_notifications_test.go
  internal/source/incoming_webhook.go
Labels: bug

#1236 Restart crashed plugins
  cmd/botkube-agent/main.go
  cmd/executor/echo/main.go
  cmd/source/cm-watcher/main.go
  helm/botkube/README.md
  helm/botkube/e2e-test-values.yaml
  helm/botkube/values.yaml
  internal/plugin/health_monitor.go
  internal/plugin/index_builder.go
  internal/plugin/manager.go
  internal/plugin/manager_test.go
  internal/plugin/store.go
  internal/source/dispatcher.go
  internal/source/scheduler.go
  internal/source/scheduler_test.go
  internal/source/testdata/TestStartingUniqueProcesses/config.yaml
  pkg/config/config.go
  pkg/config/testdata/TestLoadConfigSuccess/config.golden.yaml
  pkg/execute/config_test.go
Labels: enhancement

#1242 Fix ArgoCD template name normalization
  internal/source/argocd/argocd.go
  internal/source/argocd/default-config.yaml
  internal/source/argocd/render.go
  internal/source/argocd/render_test.go
  internal/source/argocd/setup_notifications.go
  internal/source/incoming_webhook.go
Labels: bug

#1243 Fix duplicated messages for incoming requests and marshalling `oncePer` trigger property for ArgoCD source
  go.mod
  go.sum
  helm/botkube/templates/deployment.yaml
  helm/botkube/templates/global-config.yaml
  internal/source/argocd/argocd.go
  internal/source/argocd/config.go
  internal/source/argocd/setup_notifications.go
  internal/source/incoming_webhook.go
  internal/source/scheduler.go
Labels: bug

#1246 Fix writing on closed channel in Cloud Slack
  pkg/bot/slack_cloud.go
Labels: bug

#1249 Make ArgoCD plugin resilient to concurrent `Stream` method runs (#1248)
  helm/botkube/README.md
  helm/botkube/values.yaml
  internal/source/argocd/argocd.go
  internal/source/argocd/incoming_req.go
  internal/source/argocd/render.go
  internal/source/argocd/render_test.go
  internal/source/argocd/setup_notifications.go
  internal/source/dispatcher.go
Labels: bug

#1253 Fix merging Kubernetes configuration
  internal/source/kubernetes/registration.go
  internal/source/kubernetes/router.go
  internal/source/kubernetes/router_test.go
  internal/source/kubernetes/testdata/TestRouterListMergingNestedFields/override-fields-config.yaml
  internal/source/kubernetes/testdata/TestRouterListMergingNestedFields/route-apps.v1.deployments.golden.yaml
  internal/source/kubernetes/testdata/TestRouterListMergingNestedFields/route-v1.configmaps.golden.yaml
  internal/source/kubernetes/testdata/TestRouterListMergingNestedFields/route-v1.pod.golden.yaml
Labels: bug

#1252 Fix Helm chart overrides for additional RBAC groups
  helm/botkube/README.md
  helm/botkube/templates/rbac-groups.yaml
  helm/botkube/values.yaml
Labels: bug

#1254 Kubectl plugin's binary dependencies version upgrade to v1.28.0
  go.mod
  go.sum
  internal/executor/kubectl/executor.go
Labels: enhancement

#1258 Fix issues reported by linter
  .github/workflows/ci.yml
  internal/config/remote/config.go
  internal/source/kubernetes/recommendation/resource_events_test.go
  internal/source/kubernetes/router_test.go
Labels: enhancement

#1256 Show plugin activation status
  cmd/botkube-agent/main.go
  internal/plugin/health_monitor.go
  internal/plugin/health_stats.go
  internal/plugin/manager.go
  internal/plugin/manager_test.go
  pkg/execute/exec.go
  pkg/execute/exec_test.go
  pkg/execute/executor.go
  pkg/execute/factory.go
  pkg/execute/mapping.go
  pkg/execute/source.go
  pkg/execute/source_test.go
  test/e2e/bots_test.go
Labels: enhancement

#1264 Fix panic for Cloud Slack reconnect and JSON schema for K8s configuration
  internal/source/kubernetes/config-jsonschema.json
  internal/source/kubernetes/source.go
  pkg/bot/slack_cloud.go
Labels: bug

#1267 Fix dispatching events for sink platforms
  internal/source/dispatcher.go
Labels: bug

#1265 Fix ES type setting, add ES client logging, improve plugin URL err
  helm/botkube/README.md
  helm/botkube/values.yaml
  internal/plugin/manager.go
  pkg/config/config.go
  pkg/config/testdata/TestLoadConfigSuccess/config.golden.yaml
  pkg/sink/elasticsearch.go
Labels: bug

#1268 Document Doctor configuration options in Helm values.yaml, fix custom engine override
  helm/botkube/README.md
  helm/botkube/values.yaml
  internal/executor/doctor/config-jsonschema.json
  internal/executor/doctor/executor.go
  internal/executor/flux/config.go
Labels: bug

#1261 Introduce integration tests for plugin recovery
  helm/botkube/e2e-test-values.yaml
  helm/botkube/templates/global-config.yaml
  test/e2e/bots_test.go
Labels: enhancement, ci

#1269 Cancel previous runs, bump CI deps, migrate set-output
  .github/workflows/branch-build.yml
  .github/workflows/chart-testing.yaml
  .github/workflows/ci.yml
  .github/workflows/codeql.yaml
  .github/workflows/cut-new-release.yml
  .github/workflows/finalize-release.yml
  .github/workflows/next-rc.yml
  .github/workflows/pr-build.yaml
  .github/workflows/process-chart.yml
  .github/workflows/release.yml
  .github/workflows/upload-plugins.yaml
  .github/workflows/vulnerability-scan.yml
Labels: enhancement

#1275 Fix concurrent PR jobs
  .github/workflows/chart-testing.yaml
  .github/workflows/ci.yml
  .github/workflows/codeql.yaml
  .github/workflows/pr-build.yaml
  .github/workflows/vulnerability-scan.yml
Labels: bug

#1271 Add segment analytics to CLI
  .github/workflows/release.yml
  .goreleaser.yml
  cmd/cli/README.md
  cmd/cli/cmd/config/get.go
  cmd/cli/cmd/install.go
  cmd/cli/cmd/login.go
  cmd/cli/cmd/migrate.go
  cmd/cli/cmd/root.go
  cmd/cli/cmd/telemetry/disable.go
  cmd/cli/cmd/telemetry/enable.go
  cmd/cli/cmd/telemetry/telemetry.go
  cmd/cli/cmd/uninstall.go
  cmd/cli/docs/botkube.md
  cmd/cli/docs/botkube_telemetry.md
  cmd/cli/docs/botkube_telemetry_disable.md
  cmd/cli/docs/botkube_telemetry_enable.md
  go.mod
  go.sum
  hack/goreleaser.sh
  internal/cli/analytics/cmd.go
  internal/cli/analytics/noop_reporter.go
  internal/cli/analytics/reporter.go
  internal/cli/analytics/segment_reporter.go
  internal/cli/config.go
  internal/cli/login/login.go
  internal/cli/migrate/migrate.go
Labels: enhancement

#1274 Fix configuration merging when using `existingCommunicationsSecretName`
  helm/botkube/templates/communicationsecret.yaml
  helm/botkube/templates/deployment.yaml
  helm/botkube/templates/global-config.yaml
  helm/botkube/templates/persistent-config.yaml
Labels: bug

#1205 Cloud Slack E2e Tests
  .golangci.yml
  Makefile
  helm/botkube/e2e-cloud-test-values.yaml
  helm/botkube/e2e-test-values.yaml
  test/botkubex/botkube_cli_helpers.go
  test/commplatform/discord_tester.go
  test/commplatform/generic.go
  test/commplatform/slack_tester.go
  test/e2e/bots_test.go
  test/e2e/gql_client.go
  test/e2e/slack_helpers_test.go
Labels: enhancement
