Repository kubeshop/botkube, pull requests merged in 2023-10, with the labels that each got.

#1279 Main helm chart deployment
  .github/workflows/branch-build.yml
  .github/workflows/publish-chart.yml
  hack/goreleaser.sh
Labels: enhancement, ci

#1281 Rework in-cluster ConfigWatcher to use informers instead of sidecar
  cmd/botkube-agent/main.go
  helm/botkube/README.md
  helm/botkube/templates/clusterrole.yaml
  helm/botkube/templates/deployment.yaml
  helm/botkube/templates/global-config.yaml
  helm/botkube/values.yaml
  internal/config/reloader/get.go
  internal/config/reloader/in_cluster.go
  internal/config/reloader/in_cluster_test.go
  internal/config/reloader/remote.go
  internal/lifecycle/server.go
  internal/lifecycle/server_test.go
  pkg/config/config.go
  pkg/config/testdata/TestLoadConfigSuccess/config.golden.yaml
  pkg/config/watcher_sync.go
  pkg/execute/config_test.go
  test/e2e/bots_test.go
Labels: enhancement

#1276 Healthz improve endpoint
  cmd/botkube-agent/main.go
  internal/health/health.go
  internal/health/health_test.go
  internal/health/status.go
  pkg/bot/bot.go
  pkg/bot/discord.go
  pkg/bot/mattermost.go
  pkg/bot/slack_cloud.go
  pkg/bot/slack_cloud_test.go
  pkg/bot/slack_legacy.go
  pkg/bot/slack_socket.go
  pkg/bot/teams.go
  pkg/notifier/sink.go
  pkg/sink/elasticsearch.go
  pkg/sink/webhook.go
Labels: enhancement

#1285 Fix main chart version
  .github/workflows/publish-chart.yml
Labels: bug, ci

#1287 Upload only plugin archives as latest plugins
  .github/workflows/upload-plugins.yaml
Labels: bug

#1289 Add demo video to the Acceptance Criteria for feature requests
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation, community

#1290 fix chart repo url
  .github/workflows/publish-chart.yml
Labels: bug, ci

#1288 Fix Cloud Slack Dev E2E tests after Botkube release
  test/cloud-slack-dev-e2e/cloud_slack_dev_e2e_test.go
Labels: bug, ci

#1292 Use main chart in tests
  test/cloud-slack-dev-e2e/cloud_slack_dev_e2e_test.go
  test/helmx/helm_helpers.go
Labels: enhancement, ci

#1295 Include full plugin name in reported command
  cmd/botkube-agent/main.go
  internal/analytics/noop_reporter.go
  internal/analytics/reporter.go
  internal/analytics/segment_reporter.go
  internal/analytics/segment_reporter_test.go
  internal/analytics/testdata/TestSegmentReporter_ReportBotEnabled.json
  internal/analytics/testdata/TestSegmentReporter_ReportCommand.json
  internal/analytics/testdata/TestSegmentReporter_ReportSinkEnabled.json
  internal/source/dispatcher.go
  pkg/bot/bot.go
  pkg/bot/discord.go
  pkg/bot/mattermost.go
  pkg/bot/slack_cloud.go
  pkg/bot/slack_legacy.go
  pkg/bot/slack_socket.go
  pkg/bot/teams.go
  pkg/execute/executor.go
  pkg/execute/factory.go
  pkg/sink/elasticsearch.go
  pkg/sink/types.go
  pkg/sink/webhook.go
Labels: enhancement

#1294 Add thread mate plugin
  .goreleaser.plugin.yaml
  cmd/executor/thread-mate/main.go
  go.mod
  go.sum
  internal/executor/thread-mate/cm_sync.go
  internal/executor/thread-mate/commands.go
  internal/executor/thread-mate/config.go
  internal/executor/thread-mate/jsonschema.json
  internal/executor/thread-mate/mentions.go
  internal/executor/thread-mate/messages/round-robin.yaml
  internal/executor/thread-mate/service.go
  internal/executor/thread-mate/system_data.go
  internal/executor/thread-mate/thread.go
  internal/executor/x/mathx/int.go
  internal/executor/x/output/message_tutorial.go
  internal/storage/help.go
  pkg/api/executor/executor.pb.go
  pkg/api/executor/grpc_adapter.go
  pkg/api/message.go
  pkg/bot/interactive/base_msg.go
  pkg/bot/slack_msg_tracker.go
  pkg/bot/slack_shared.go
  pkg/bot/slack_socket.go
  pkg/config/config.go
  pkg/config/testdata/TestLoadConfigSuccess/config.golden.yaml
  pkg/execute/factory.go
  pkg/execute/plugin_executor.go
  proto/executor.proto
Labels: enhancement

#1297 Add MS Teams apps for sideloading
  assets/ms-teams/Botkube.zip
  assets/ms-teams/BotkubeDev.zip
  assets/ms-teams/README.md
Labels: enhancement

#1298 Add cloud teams integration
  cmd/botkube-agent/main.go
  internal/plugin/collector.go
  internal/source/scheduler.go
  pkg/api/cloudplatform/creds.go
  pkg/api/cloudslack/cloud_slack.pb.go
  pkg/api/cloudslack/cloud_slack_grpc.pb.go
  pkg/api/cloudteams/cloud_teams.pb.go
  pkg/api/cloudteams/cloud_teams_grpc.pb.go
  pkg/bot/bot.go
  pkg/bot/slack_cloud.go
  pkg/bot/teams_cloud.go
  pkg/bot/teams_cloud_grpc.go
  pkg/config/config.go
  proto/cloud_slack.proto
  proto/cloud_teams.proto
Labels: enhancement

#1300 Update thread-mate schema, fix setting emoji indicator
  internal/executor/thread-mate/config.go
  internal/executor/thread-mate/jsonschema.json
  pkg/bot/slack_socket.go
  pkg/config/config.go
Labels: bug

#1304 Cloud MS Teams now using remote cfg
  pkg/bot/teams_cloud_grpc.go
Labels: enhancement
