Repository kubeshop/botkube, pull requests merged in 2023-12, with the labels that each got.

#1324 Added new org env var for prod e2e test
  .github/workflows/prod-e2e-test.yml
Labels: other

#1325 ignore empty botkube repositories url during cli test
  test/helmx/helm_helpers.go
Labels: other

#1328 Update JSON schemas for all plugins
  cmd/executor/echo/config_schema.json
  cmd/executor/echo/main.go
  cmd/executor/exec/main.go
  cmd/executor/gh/config_schema.json
  cmd/executor/gh/main.go
  cmd/executor/thread-mate/main.go
  cmd/source/cm-watcher/config_schema.json
  cmd/source/cm-watcher/main.go
  cmd/source/cm-watcher/webhook_schema.json
  internal/executor/doctor/config_schema.json
  internal/executor/doctor/executor.go
  internal/executor/flux/config.go
  internal/executor/flux/config_schema.json
  internal/executor/flux/executor.go
  internal/executor/flux/jsonschema.json
  internal/executor/helm/config.go
  internal/executor/helm/config_schema.json
  internal/executor/helm/executor.go
  internal/executor/kubectl/config.go
  internal/executor/kubectl/config_schema.json
  internal/executor/kubectl/executor.go
  internal/executor/thread-mate/config.go
  internal/executor/thread-mate/config_schema.json
  internal/executor/x/config.go
  internal/executor/x/config_schema_fmt.json
  internal/source/argocd/argocd.go
  internal/source/argocd/config.go
  internal/source/argocd/config_schema.json
  internal/source/github_events/config_schema.json
  internal/source/github_events/source_grpc.go
  internal/source/keptn/config.go
  internal/source/keptn/config_schema.json
  internal/source/keptn/source.go
  internal/source/kubernetes/config_schema.json
  internal/source/kubernetes/source.go
  internal/source/prometheus/config_schema.json
  internal/source/prometheus/source.go
Labels: enhancement

#1330 Add origin extraction for cmd execution, add user display name for interactive command
  internal/remote/graphql/connected_platforms.go
  internal/remote/graphql/models_gen.go
  internal/remote/graphql/platforms.go
  internal/remote/graphql/usage.go
  pkg/bot/teams_cloud.go
  pkg/bot/teams_cloud_test.go
  pkg/execute/command/origin.go
Labels: enhancement

#1332 Support TLS encryption for gRPC connections in Cloud Slack and Teams
  pkg/bot/slack_cloud.go
  pkg/bot/teams_cloud.go
  pkg/bot/teams_cloud_grpc.go
  pkg/config/config.go
  pkg/grpcx/credentials.go
Labels: enhancement

#1335 Fix Cloud Slack Dev E2E tests after GQL model changes
  .github/workflows/prod-e2e-test.yml
  .github/workflows/publish-chart.yml
  test/cloud-slack-dev-e2e/cloud_slack_dev_e2e_test.go
  test/cloud-slack-dev-e2e/gql.go
  test/cloud_graphql/graphql_client.go
  test/cloud_graphql/model/connected_platforms.go
  test/cloud_graphql/model/doc.go
  test/cloud_graphql/model/models_gen.go
  test/cloud_graphql/model/platforms.go
  test/cloud_graphql/model/usage.go
Labels: bug

#1340 Fix redacting credentials and hide CA certificate when showing config
  pkg/config/config.go
  pkg/execute/config.go
Labels: bug

#1339 ADD recommended flag to plugin index
  internal/executor/doctor/executor.go
  internal/executor/flux/executor.go
  internal/executor/helm/executor.go
  internal/executor/kubectl/executor.go
  internal/plugin/index.go
  internal/plugin/index_builder.go
  internal/plugin/store.go
  internal/source/argocd/argocd.go
  internal/source/github_events/source_grpc.go
  internal/source/keptn/source.go
  internal/source/kubernetes/source.go
  internal/source/prometheus/source.go
  pkg/api/executor/executor.pb.go
  pkg/api/executor/grpc_adapter.go
  pkg/api/plugin.go
  pkg/api/source/grpc_adapter.go
  pkg/api/source/source.pb.go
  proto/executor.proto
  proto/source.proto
Labels: enhancement
