Repository kubeshop/botkube, pull requests merged in 2024-01, with the labels that each got.

#1342 Fix slight confusion in agent built bin name
  CONTRIBUTING.md
  Makefile
Labels: documentation, contributor experience

#1345 Update GraphQL models used for remote config tests
  README.md
  internal/remote/graphql/models_gen.go
Labels: bug

#1341 Forward action output to sinks
  internal/source/dispatcher.go
Labels: enhancement

#1346 Run the Cloud Slack E2E test every hour
  .github/workflows/prod-e2e-test.yml
Labels: ci, other

#1347 Update Slack E2E tests with full workspace reconnect flow
  .github/workflows/branch-build.yml
  test/README.md
  test/cloud-slack-dev-e2e/cloud_slack_dev_e2e_test.go
Labels: ci, other

#1349 Update Doctor's engine to `gpt-3.5-turbo-instinct` and fix prompt
  go.mod
  go.sum
  internal/executor/doctor/config_schema.json
  internal/executor/doctor/executor.go
Labels: bug

#1351 Update README.md with new description
  README.md
Labels: documentation

#1352 Improve Cloud Slack e2e test resiliency around Slack workspace connect
  test/cloud-slack-dev-e2e/cloud_slack_dev_e2e_test.go
Labels: ci, other

#1353 Fix Botkube version constraint during migration
  cmd/cli/cmd/migrate.go
  cmd/cli/docs/botkube_migrate.md
  test/cloud-slack-dev-e2e/cloud_slack_dev_e2e_test.go
  test/e2e/migration_test.go
Labels: bug

#1354 Update Cloud Slack E2E tests with plugin `enable`/`disable`
  internal/remote/graphql/models_gen.go
  test/cloud-slack-dev-e2e/cloud_slack_dev_e2e_test.go
  test/cloud_graphql/graphql_client.go
  test/commplatform/slack_tester.go
  test/e2e/gql_client.go
Labels: ci, other

#1355 Migrate disabled plugins to Cloud
  helm/botkube/README.md
  helm/botkube/values.yaml
  internal/cli/install/helm/install.go
  internal/cli/install/install.go
  internal/cli/migrate/converter.go
  pkg/config/config.go
  pkg/config/testdata/TestLoadConfigSuccess/config.golden.yaml
  pkg/config/testdata/TestLoadConfigSuccess/executors.yaml
Labels: bug, enhancement

#1357 Migration tests
  test/e2e/migration_test.go
Labels: enhancement

#1362 Reorganize migrate constaints check and add unit tests
  cmd/cli/cmd/migrate.go
  go.mod
  internal/cli/migrate/compatibility.go
  internal/cli/migrate/compatibility_test.go
Labels: other

#1363 Fix Botkube installation `exec` config for the migration tests
  test/e2e/migration_test.go
  test/helmx/helm_helpers.go
Labels: ci, other

#1365 Fix branch-build.yml workflow
  .github/workflows/branch-build.yml
Labels: bug
