Repository kubeshop/botkube, pull requests merged in 2024-11, with the labels that each got.

#1476 Update README.md
  README.md
Labels: documentation

#1480 Update Socket Slack app upload API
  go.mod
  go.sum
  helm/botkube/README.md
  helm/botkube/values.yaml
  pkg/bot/slack_cloud.go
  pkg/bot/slack_socket.go
  test/go.mod
  test/go.sum
Labels: enhancement

#1481 Fix panic on missing root event type for k8s source
  internal/source/kubernetes/router.go
  internal/source/kubernetes/router_test.go
Labels: bug

#1483 Remove latest plugin upload to GCS
  .github/workflows/upload-plugins.yaml
  helm/botkube/README.md
  helm/botkube/values.yaml
Labels: bug
