Repository kubeshop/botkube, pull requests merged in 2024-02, with the labels that each got.

#1366 Share the cloud slack e2e workflow between jobs
  .github/actions/cloud-slack-e2e/action.yaml
  .github/workflows/branch-build.yml
  .github/workflows/prod-e2e-test.yml
  test/cloud-slack-dev-e2e/cloud_slack_dev_e2e_test.go
  test/go.mod
  test/go.sum
  test/helmx/helm_helpers.go
  test/helmx/redact_test.go
Labels: enhancement

#1369 Bump github.com/gin-gonic/gin from 1.8.1 to 1.9.1
  .github/workflows/ci.yml
  go.mod
  go.sum
  hack/fmt-imports.sh
  test/go.mod
  test/go.sum
Labels: dependencies, other

#1373 Move plugin-related internal packages to `pkg`
  internal/executor/flux/config.go
  internal/executor/x/config.go
  internal/executor/x/run.go
  internal/executor/x/run_test.go
  internal/plugin/index.go
  internal/source/argocd/setup_notifications.go
  internal/source/kubernetes/event/event.go
  internal/source/kubernetes/k8sutil/resource.go
  internal/source/kubernetes/recommendation/ingress_backend_service_valid.go
  internal/source/kubernetes/recommendation/ingress_tls_secret_valid.go
  internal/source/kubernetes/recommendation/pod_labels_set.go
  internal/source/kubernetes/recommendation/pod_no_latest_image_tag.go
  internal/source/kubernetes/registration.go
  pkg/config/plugin.go
  pkg/k8sx/resource.go
  pkg/pluginx/tmp_dir.go
  pkg/stringx/indent.go
  pkg/stringx/indent_test.go
Labels: refactor, other

#1372 Update Cloud Slack to always respond in a thread
  .github/actions/setup-go-mod-private/action.yaml
  .github/workflows/branch-build.yml
  .github/workflows/prod-e2e-test.yml
  pkg/bot/slack_cloud.go
  pkg/bot/slack_shared.go
  test/cloud-slack-dev-e2e/cloud_slack_dev_e2e_test.go
  test/commplatform/discord_tester.go
  test/commplatform/generic.go
  test/commplatform/slack_tester.go
  test/commplatform/teams_tester.go
  test/e2e/bots_test.go
Labels: enhancement

#1375 Update setup-go action
  .github/actions/setup-go-mod-private/action.yaml
  .github/workflows/branch-build.yml
  .github/workflows/ci.yml
  .github/workflows/codeql.yaml
  .github/workflows/pr-build.yaml
  .github/workflows/release.yml
  .github/workflows/upload-plugins.yaml
  test/cloud-slack-dev-e2e/cloud_slack_dev_e2e_test.go
  test/commplatform/discord_tester.go
  test/commplatform/generic.go
  test/commplatform/slack_tester.go
  test/commplatform/teams_tester.go
Labels: ci, other

#1374 Enabled Plugins Report
  cmd/botkube-agent/main.go
  internal/analytics/noop_reporter.go
  internal/analytics/reporter.go
  internal/analytics/segment_reporter.go
  internal/analytics/segment_reporter_test.go
  internal/analytics/testdata/TestSegmentReporter_ReportPluginsEnabled.json
  internal/plugin/kubeconfig.go
  pkg/config/config.go
Labels: enhancement

#1377 Fix a tiny typo
  cmd/botkube-agent/main.go
Labels: bug

#1380 Fix kubectl builder perms checker
  Makefile
  internal/executor/kubectl/accessreview/review.go
  internal/executor/kubectl/builder/deps.go
  internal/executor/kubectl/builder/kubectl.go
  internal/executor/kubectl/builder/kubectl_test.go
  internal/executor/kubectl/builder/review.go
  internal/executor/kubectl/executor.go
  test/helpers/plugin_server.go
Labels: bug

#1378 Fix Helm chart upgrade when using existing secret
  helm/botkube/templates/persistent-config.yaml
Labels: bug

#1384 Enhance Slack notification footer
  .github/actions/cloud-slack-e2e/action.yaml
  .github/workflows/branch-build.yml
  .github/workflows/prod-e2e-test.yml
Labels: enhancement

#1385 Update executor contract, publish local dev server
  CONTRIBUTING.md
  hack/target/serve-plugins/main.go
  pkg/api/executor/executor.pb.go
  pkg/api/executor/grpc_adapter.go
  pkg/api/message.go
  pkg/api/source/grpc_adapter.go
  pkg/bot/slack_socket.go
  pkg/execute/factory.go
  pkg/execute/plugin_executor.go
  pkg/plugin/plugin_server.go
  proto/executor.proto
  test/e2e/bots_test.go
  test/helpers/plugin_server.go
Labels: enhancement

#1387 Add teams and slack parent activity id support, remove not used activityId field from gRPC
  pkg/api/cloudteams/cloud_teams.pb.go
  pkg/bot/slack_cloud.go
  pkg/bot/teams_cloud.go
  proto/cloud_teams.proto
Labels: enhancement

#1388 Bump helm.sh/helm/v3 from 3.13.2 to 3.14.1
  go.mod
  go.sum
  test/go.mod
  test/go.sum
Labels: dependencies, other

#1381 Support custom headers during plugin index request
  go.mod
  go.sum
  helm/botkube/README.md
  helm/botkube/values.yaml
  internal/cli/migrate/converter.go
  pkg/config/config.go
  pkg/config/testdata/TestLoadConfigSuccess/config.golden.yaml
  pkg/plugin/downloader.go
  pkg/plugin/index.go
  pkg/plugin/manager.go
  pkg/plugin/manager_test.go
  pkg/templatex/render.go
  test/go.mod
  test/go.sum
Labels: enhancement

#1392 Fix migration CI job and remove unused `lifecycleServer` properties
  helm/botkube/README.md
  helm/botkube/templates/service.yaml
  helm/botkube/templates/systemroles.yaml
  helm/botkube/values.yaml
  internal/cli/migrate/converter.go
  pkg/config/config.go
  pkg/config/testdata/TestLoadConfigSuccess/config.golden.yaml
  pkg/execute/config_test.go
  test/e2e/migration_test.go
Labels: ci, other

#1396 Ignore upgrade checker error
  cmd/botkube-agent/main.go
Labels: bug

#1397 Fix executor assertion for integration tests
  test/e2e/bots_test.go
Labels: ci, other

#1401 Fix overwriting custom RBAC config and Kubernetes plugin JSON schema
  helm/botkube/README.md
  helm/botkube/values.yaml
  internal/analytics/segment_reporter.go
  internal/analytics/segment_reporter_test.go
  internal/analytics/testdata/TestSegmentReporter_ReportPluginsEnabled.json
  internal/executor/kubectl/executor.go
  internal/source/kubernetes/config_schema.json
Labels: bug

#1402 Apply patches for 1.9.1
  helm/botkube/README.md
  helm/botkube/values.yaml
  internal/analytics/segment_reporter.go
  internal/analytics/segment_reporter_test.go
  internal/analytics/testdata/TestSegmentReporter_ReportPluginsEnabled.json
  internal/executor/kubectl/executor.go
  internal/source/kubernetes/config_schema.json
Labels: bug
