Repository kubeshop/botkube, pull requests merged in 2024-04, with the labels that each got.

#1425 Reduce memory consumption for Kubernetes source configuration
  cmd/botkube-agent/main.go
  internal/source/dispatcher.go
  internal/source/kubernetes/bg_processor.go
  internal/source/kubernetes/configuration_store.go
  internal/source/kubernetes/filterengine/filterengine.go
  internal/source/kubernetes/registration.go
  internal/source/kubernetes/router.go
  internal/source/kubernetes/router_test.go
  internal/source/kubernetes/source.go
  internal/source/kubernetes/testdata/TestRouterListMergingNestedFields/route-apps.v1.deployments.golden.yaml
  internal/source/kubernetes/testdata/TestRouterListMergingNestedFields/route-v1.configmaps.golden.yaml
  internal/source/kubernetes/testdata/TestRouterListMergingNestedFields/route-v1.pod.golden.yaml
  internal/source/scheduler.go
Labels: enhancement

#1428 Run Cloud Prod E2E tests every 2 hours
  .github/workflows/prod-e2e-test.yml
Labels: ci, other

#1429 Fix Teams integration tests assertions
  test/commplatform/teams_tester.go
  test/e2e/bots_test.go
Labels: bug, ci

#1431 Add retries for resources cleanup in Botkube E2E and integration tests
  test/cloud-slack-dev-e2e/cloud_slack_dev_e2e_test.go
  test/cloud_graphql/graphql_client.go
  test/e2e/bots_test.go
  test/go.mod
Labels: other

#1433 Add single quote escaping while parsing input command
  pkg/execute/executor.go
  pkg/execute/params.go
  pkg/execute/params_test.go
Labels: bug

#1435 Fix integration and E2E tests after Cloud Dev update
  test/cloud-slack-dev-e2e/cloud_slack_dev_e2e_test.go
  test/cloud_graphql/graphql_client.go
  test/commplatform/slack_tester.go
  test/e2e/bots_test.go
  test/e2e/gql_client.go
  test/go.mod
  test/go.sum
  test/msg-layouts/help_test.go
Labels: bug

#1436 Add `api.BasicCardWithButtonsInSeparateMsg` type
  pkg/api/message.go
Labels: enhancement
