Repository kubeshop/botkube, pull requests merged in 2024-07, with the labels that each got.

#1465 Add link to exact run
  .github/actions/cloud-slack-e2e/action.yaml
  .github/workflows/branch-build.yml
  .github/workflows/prod-e2e-test.yml
Labels: enhancement, ci

#1466 Improve stability of Slack E2E tests
  test/cloud-slack-dev-e2e/botkube_page_helpers_test.go
Labels: ci, other

#1467 Hide private channel names in `show config` command
  pkg/bot/slack_cloud.go
  pkg/config/config.go
  pkg/config/redacted.go
  pkg/execute/config.go
Labels: enhancement

#1469 Hearbeat reporting
  cmd/botkube-agent/main.go
  internal/health/failed.go
  internal/health/health.go
  internal/health/health_test.go
  internal/health/status.go
  internal/heartbeat/gql_reporter.go
  internal/heartbeat/noop_reporter.go
  internal/heartbeat/reporter.go
  internal/insights/k8s_collector.go
  pkg/bot/discord.go
  pkg/bot/mattermost.go
  pkg/bot/slack_cloud.go
  pkg/bot/slack_socket.go
  pkg/bot/teams_cloud.go
  pkg/notifier/platform.go
  pkg/sink/elasticsearch.go
  pkg/sink/pager_duty.go
  pkg/sink/webhook.go
Labels: enhancement
