Repository kubeshop/botkube, pull requests merged in 2024-06, with the labels that each got.

#1457 Add support for --kube-context option into botkube CLI
  cmd/cli/docs/botkube_install.md
  cmd/cli/docs/botkube_migrate.md
  cmd/cli/docs/botkube_uninstall.md
  internal/cli/helmx/action_cfg.go
  internal/cli/install/helm/install.go
  internal/cli/install/install.go
  internal/cli/uninstall/helm/uninstall.go
  internal/cli/uninstall/uninstall.go
  internal/kubex/config.go
Labels: enhancement

#1458 Add setting up an Instance via the UI instead of GraphQL
  .github/actions/cloud-slack-e2e/action.yaml
  .github/workflows/branch-build.yml
  .github/workflows/prod-e2e-test.yml
  test/cloud-slack-dev-e2e/botkube_page_helpers_test.go
  test/cloud-slack-dev-e2e/cloud_slack_dev_e2e_test.go
  test/cloud-slack-dev-e2e/gql.go
  test/cloud-slack-dev-e2e/page_helpers_test.go
  test/cloud-slack-dev-e2e/slack_page_helpers_test.go
  test/go.mod
Labels: enhancement, test-framework

#1460 Update GitHub actions
  .github/actions/cloud-slack-e2e/action.yaml
  .github/actions/dump-cluster/action.yaml
Labels: dependencies, other

#1462 Add missing UI URL for prod tests
  .github/actions/cloud-slack-e2e/action.yaml
  .github/workflows/branch-build.yml
  .github/workflows/prod-e2e-test.yml
Labels: bug

#1461 Fix and enable instance details page UI tests
  test/cloud-slack-dev-e2e/botkube_page_helpers_test.go
  test/cloud-slack-dev-e2e/cloud_slack_dev_e2e_test.go
  test/cloud-slack-dev-e2e/slack_page_helpers_test.go
Labels: ci, other

#1463 Add early cleanup for Slack E2E tests
  test/cloud-slack-dev-e2e/botkube_page_helpers_test.go
  test/cloud-slack-dev-e2e/cloud_slack_dev_e2e_test.go
  test/cloud-slack-dev-e2e/page_helpers_test.go
  test/cloud-slack-dev-e2e/slack_page_helpers_test.go
Labels: ci, other
