Repository kubeshop/botkube, pull requests merged in 2024-05, with the labels that each got.

#1439 Add information about storing mentions and event in audit logs
  pkg/api/message.go
  pkg/bot/interactive/help.go
  pkg/bot/slack_renderer.go
  test/msg-layouts/help_test.go
  test/msg-layouts/testdata/TestNewHelpMessage/cloud-slack-help.golden.json
  test/msg-layouts/testdata/TestNewHelpMessage/cloud-teams-help.golden.json
Labels: enhancement

#1440 Update go.mod in test pkg
  test/go.mod
  test/go.sum
Labels: other

#1441 fix: close temporary kubeconfig file
  pkg/plugin/kubeconfig.go
Labels: bug

#1444 Add Slack home tab assets
  assets/slack/slack-home-tab-argocd.png
  assets/slack/slack-home-tab-k8s-alert.png
Labels: enhancement

#1443 Update support button for Cloud Slack and Teams
  pkg/bot/interactive/help.go
  pkg/bot/interactive/testdata/TestInteractiveMessageToMarkdown/render_with_custom_headers_and_default_new_lines.golden.txt
  pkg/bot/interactive/testdata/TestInteractiveMessageToMarkdown/render_with_custom_new_lines_and_default_headers.golden.txt
  pkg/bot/interactive/testdata/TestInteractiveMessageToPlaintext.golden.txt
  test/msg-layouts/testdata/TestNewHelpMessage/cloud-slack-help.golden.json
  test/msg-layouts/testdata/TestNewHelpMessage/cloud-teams-help.golden.json
  test/msg-layouts/testdata/TestNewHelpMessage/discord-help.golden.md
  test/msg-layouts/testdata/TestNewHelpMessage/mattermost-help.golden.md
Labels: enhancement

#1445 Update Helm chart description and error wording
  helm/botkube/Chart.yaml
  helm/botkube/README.md
  helm/botkube/values.yaml
  pkg/bot/slack_cloud.go
  pkg/bot/slack_socket.go
Labels: other

#1446 Add PagerDuty integration platform
  cmd/botkube-agent/main.go
  go.mod
  go.sum
  internal/source/scheduler.go
  pkg/config/config.go
  pkg/plugin/collector.go
  pkg/sink/pager_duty.go
  pkg/sink/pager_duty_meta.go
  pkg/sink/pager_duty_test.go
  test/go.mod
  test/go.sum
Labels: enhancement

#1447 Remove packages for Botkube app for Microsoft Teams
  assets/ms-teams/Botkube.zip
  assets/ms-teams/BotkubeDev.zip
  assets/ms-teams/README.md
Labels: other

#1448 Update links in Helm chart values file
  helm/botkube/README.md
  helm/botkube/values.yaml
Labels: bug

#1449 Update Helm chart Readme links rendering
  helm/botkube/README.md
  helm/botkube/README.tpl.md
Labels: documentation

#1450 Introduce italic description for Button Builder API
  pkg/api/message.go
  pkg/bot/slack_renderer.go
Labels: other

#1451 bot: add cluster scan help docs
  pkg/bot/interactive/help.go
Labels: documentation
